'use strict';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEYS={race:'legionrx4_current_race',pilots:'legionrx4_pilot_db',champ:'legionrx4_championships',archive:'legionrx4_archive',settings:'legionrx4_settings'};
const defaultUi={cardRadius:14,tileRadius:14,buttonRadius:9,inputRadius:8,iconRadius:10,heroRadius:18,widgetRadius:12,modalRadius:14,cardPadding:18,sectionGap:14,buttonHeight:48,contentWidth:1240,disciplineCols:3};
const defaultSettings={theme:'light',lang:'ru',lapSound:true,minLapSec:2,qualificationMinutes:5,finalLaps:7,countdownSec:5,ui:{...defaultUi}};
const I18N={
 ru:{'nav.home':'Главная','nav.champs':'Чемпионаты','nav.pilots':'Пилоты','nav.settings':'Настройки'},
 en:{'nav.home':'Home','nav.champs':'Championships','nav.pilots':'Drivers','nav.settings':'Settings'}
};
const storedSettings=load(KEYS.settings,{});
const state={view:'home',race:load(KEYS.race,null),pilotDb:load(KEYS.pilots,[]),championships:load(KEYS.champ,[]),archive:load(KEYS.archive,[]),settings:{...defaultSettings,...storedSettings,ui:{...defaultUi,...(storedSettings.ui||{})}},session:null,sessionTick:null,countdownTick:null,resultsOpen:false,mobileEvents:false,mobileWidgets:false};
const lapwiz=new LapWizCore();
lapwiz.sound=state.settings.lapSound;

function load(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback;}catch{return fallback;}}
function save(key,v){localStorage.setItem(key,JSON.stringify(v));}
function persistRace(){if(state.race){state.race.updatedAt=new Date().toISOString();save(KEYS.race,state.race);}updateHeader();}
function persistAll(){save(KEYS.pilots,state.pilotDb);save(KEYS.champ,state.championships);save(KEYS.archive,state.archive);save(KEYS.settings,state.settings);persistRace();}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200);}
function fmtMs(ms){if(!Number.isFinite(ms))return'—';const s=Math.max(0,ms)/1000,m=Math.floor(s/60),sec=Math.floor(s%60),cs=Math.floor((s-Math.floor(s))*100);return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${String(cs).padStart(2,'0')}`;}
function fmtClock(ms){if(!Number.isFinite(ms))return'00:00';const t=Math.ceil(Math.max(0,ms)/1000),m=Math.floor(t/60),s=t%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function nameInitials(name=''){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'RX';}
function uiIcon(name,cls='uiIcon'){
 const paths={
  flag:'<path d="M5 21V5m0 0c5-3 8 3 14 0v9c-6 3-9-3-14 0"/>',
  timer:'<circle cx="12" cy="13" r="8"/><path d="M9 2h6M12 13l3-3M12 5v2"/>',
  car:'<path d="M3 15l2-6h14l2 6v4h-2m-14 0H3v-4h18v4h-2M7 19h10"/><circle cx="7" cy="16" r="1.5"/><circle cx="17" cy="16" r="1.5"/>',
  trophy:'<path d="M8 4h8v4a4 4 0 0 1-8 0V4Z"/><path d="M8 6H4v1a4 4 0 0 0 4 4m8-5h4v1a4 4 0 0 1-4 4M12 12v5m-4 3h8"/>',
  users:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c0-4 3-7 6-7s6 3 6 7m1-5c3 0 5 2 5 5"/>',
  settings:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1-2-4-2 1a7 7 0 0 0-2-1l-.3-2h-5l-.3 2a7 7 0 0 0-2 1l-2-1-2 4 2 1a7 7 0 0 0 0 2l-2 1 2 4 2-1a7 7 0 0 0 2 1l.3 2h5l.3-2a7 7 0 0 0 2-1l2 1 2-4-2-1c.1-.3.1-.7.1-1Z"/>',
  bluetooth:'<path d="M7 7l10 10-5 4V3l5 4L7 17"/>',
  chart:'<path d="M4 20V10m6 10V4m6 16v-7m4 7H2"/>',
  calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4m8-4v4M3 10h18"/>',
  mic:'<rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3m-4 0h8"/>',
  monitor:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>',
  home:'<path d="M3 11l9-8 9 8v10h-6v-6H9v6H3Z"/>',
  play:'<path d="M8 5v14l11-7Z"/>',
  chevron:'<path d="M9 18l6-6-6-6"/>'
 };
 return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.flag}</svg>`;
}
function translateStatic(){
 const d=I18N[state.settings.lang]||I18N.ru;$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(d[k])el.textContent=d[k];});
 if(state.settings.lang!=='en')return;
 const map={
  'Нет активной гонки':'No active race','Главная':'Home','Чемпионаты':'Championships','Пилоты':'Drivers','Настройки':'Settings','Текущая гонка →':'Current race →','Ралли-кросс':'RallyCross','Создать соревнование':'Create event','Открыть RallyCross':'Open RallyCross','Ралли-спринт':'Rally Sprint','Классическая RC-гонка':'Classic RC race','В разработке':'In development','Открыть':'Open','Общая база':'Driver database','Новый профиль':'New profile','Сохранить':'Save','Название':'Name','Дата':'Date','Место':'Location','Чемпионат':'Championship','Клубная гонка':'Club race','Создать событие':'Create event','Участники':'Participants','Из базы':'From database','＋ Новый':'＋ New','Формат RallyCross':'RallyCross format','Квалификационных серий':'Qualifying rounds','Квалификация, минут':'Qualifying, minutes','Финал, кругов':'Final, laps','Минимальный круг LapWiz, сек':'LapWiz minimum lap, sec','Сформировать заезды и открыть пульт':'Build heats and open control','Удалить событие':'Delete event','Открыть пульт':'Open control','СОБЫТИЯ':'EVENTS','Ход соревнования':'Event flow','ТЕКУЩИЙ ЗАЕЗД':'CURRENT HEAT','Результаты заезда':'Heat results','Таблицы':'Tables','Текущий результат':'Current result','РЕЗУЛЬТАТЫ':'RESULTS','СТАРТ':'START','ФИНИШ':'FINISH','СТОП':'STOP','ПАУЗА':'PAUSE','Подключить':'Connect','Отключить':'Disconnect','Подключить LapWiz':'Connect LapWiz','Отключить LapWiz':'Disconnect LapWiz','Интерфейс':'Interface','Тёмная тема':'Dark theme','Язык интерфейса':'Interface language','Звук прохода':'Pass sound','Значения по умолчанию':'Defaults','О приложении':'About','Сезоны':'Seasons','Мои чемпионаты':'My championships','Новый чемпионат':'New championship','План этапов':'Planned rounds','Создать':'Create','Нет завершённых этапов.':'No completed rounds.','Результаты':'Results','Завершённые заезды':'Completed heats','Итоговый протокол':'Final classification','Квалификационный рейтинг':'Qualifying ranking','Сохранить и перейти дальше':'Save and go to next heat'
 };
 const root=document.getElementById('viewHost');if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{const raw=n.nodeValue,trim=raw.trim();if(map[trim])n.nodeValue=raw.replace(trim,map[trim]);});
}
function applyUiTokens(ui=state.settings.ui){const r=document.documentElement.style;r.setProperty('--radius-card',`${ui.cardRadius}px`);r.setProperty('--radius-tile',`${ui.tileRadius}px`);r.setProperty('--radius-button',`${ui.buttonRadius}px`);r.setProperty('--radius-input',`${ui.inputRadius}px`);r.setProperty('--radius-icon',`${ui.iconRadius}px`);r.setProperty('--radius-hero',`${ui.heroRadius}px`);r.setProperty('--radius-widget',`${ui.widgetRadius}px`);r.setProperty('--radius-modal',`${ui.modalRadius}px`);r.setProperty('--card-padding',`${ui.cardPadding}px`);r.setProperty('--section-gap',`${ui.sectionGap}px`);r.setProperty('--control-height',`${ui.buttonHeight}px`);r.setProperty('--content-width',`${ui.contentWidth}px`);r.setProperty('--discipline-cols',String(ui.disciplineCols));}
function applySettings(){document.documentElement.dataset.theme=state.settings.theme;document.documentElement.lang=state.settings.lang;lapwiz.sound=state.settings.lapSound;applyUiTokens();translateStatic();}
function updateHeader(){const race=state.race;$('#headerRace').textContent=race?`${race.eventName} · ${stageLabel(race.stage)}`:'Нет активной гонки';const el=$('#headerLapwiz');el.textContent=lapwiz.connected?`LapWiz · ${lapwiz.device?.name||'подключён'}`:'LapWiz · не подключён';el.className=`statusPill ${lapwiz.connected?'good':'neutral'}`;}
function stageLabel(stage){return({setup:'Настройка',qualifying:'Квалификация',tie:'Жеребьёвка',finals:'Финалы',finished:'Завершено'})[stage]||stage;}

function nav(view){state.view=view;document.body.classList.toggle('cockpitMode',view==='cockpit');$$('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render();}
$('#brandBtn').addEventListener('click',()=>nav('home'));$('#settingsBtn').addEventListener('click',()=>nav('settings'));$$('#bottomNav button').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.view)));

function render(){clearIntervalsIfNotCockpit();const host=$('#viewHost');if(state.view==='home')host.innerHTML=homeView();else if(state.view==='rallySetup')host.innerHTML=rallySetupView();else if(state.view==='cockpit')host.innerHTML=cockpitView();else if(state.view==='championships')host.innerHTML=championshipsView();else if(state.view==='pilots')host.innerHTML=pilotsView();else if(state.view==='settings')host.innerHTML=settingsView();bindView();updateHeader();applySettings();}
function clearIntervalsIfNotCockpit(){if(state.view!=='cockpit'){if(state.sessionTick){clearInterval(state.sessionTick);state.sessionTick=null;}if(state.countdownTick){clearInterval(state.countdownTick);state.countdownTick=null;}}}

function homeView(){
 const race=state.race;
 return `<section class="page homePage">
 <div class="heroPanel">
   <div class="heroCopy"><div class="sectionLabel">RACE MANAGEMENT SYSTEM</div><h1>LEGION <span>RX</span></h1><p>Единая система проведения RC-соревнований: пилоты, заезды, результаты и LapWiz — в одном интерфейсе.</p></div>
   <div class="heroStatus">${race?`<div class="liveCard"><span class="liveDot"></span><div><small>АКТИВНОЕ СОБЫТИЕ</small><b>${esc(race.eventName)}</b><span>${stageLabel(race.stage)}</span></div><button class="btn primary" data-action="open-current">Продолжить ${uiIcon('chevron','btnIcon')}</button></div>`:`<div class="heroMini"><b>4.0.4 ALPHA</b><span>Новая оболочка · RallyCross активен</span></div>`}</div>
 </div>
 <div class="homeSectionHead"><div><div class="sectionLabel">ДИСЦИПЛИНЫ</div><h2>Выберите формат соревнования</h2></div></div>
 <div class="disciplineGrid">
  <article class="disciplineTile activeDiscipline"><div class="tileTop"><div class="tileIcon">${uiIcon('flag')}</div><span class="badge liveBadge"><span class="liveDot"></span>АКТИВНО</span></div><div><h3>Ралли-кросс</h3><p>Квалификации, очки, LCQ, переходы и финалы. Рабочий спортивный модуль.</p></div><button class="tileAction" data-action="open-rx"><span>${race?'Открыть соревнование':'Создать соревнование'}</span>${uiIcon('chevron')}</button></article>
  <article class="disciplineTile locked"><div class="tileTop"><div class="tileIcon">${uiIcon('timer')}</div><span class="badge soon">СКОРО</span></div><div><h3>Ралли-спринт</h3><p>Одиночные попытки, лучшее время и протокол результатов.</p></div><button class="tileAction" disabled><span>В разработке</span>${uiIcon('chevron')}</button></article>
  <article class="disciplineTile locked"><div class="tileTop"><div class="tileIcon">${uiIcon('car')}</div><span class="badge soon">СКОРО</span></div><div><h3>Классическая RC-гонка</h3><p>Practice, seeding, qualifying и A/B/C Finals по классической RC-логике.</p></div><button class="tileAction" disabled><span>В разработке</span>${uiIcon('chevron')}</button></article>
 </div>
 <div class="homeSectionHead modulesHead"><div><div class="sectionLabel">СИСТЕМА</div><h2>Общие разделы</h2></div></div>
 <div class="moduleGrid">
  <button class="moduleCard" data-nav="championships"><span class="moduleIcon">${uiIcon('trophy')}</span><span><small>СЕЗОНЫ И ЭТАПЫ</small><b>Чемпионаты</b><em>Турнирные таблицы и очки этапов</em></span>${uiIcon('chevron','moduleArrow')}</button>
  <button class="moduleCard" data-nav="pilots"><span class="moduleIcon">${uiIcon('users')}</span><span><small>ОБЩАЯ БАЗА</small><b>Пилоты</b><em>${state.pilotDb.length} профилей · транспондеры</em></span>${uiIcon('chevron','moduleArrow')}</button>
  <button class="moduleCard" data-nav="settings"><span class="moduleIcon">${uiIcon('settings')}</span><span><small>СИСТЕМА</small><b>Настройки</b><em>Тема, язык, LapWiz, о приложении</em></span>${uiIcon('chevron','moduleArrow')}</button>
 </div>
 </section>`;
}

function rallySetupView(){
 const race=state.race;const step=race?.stage||'setup';return `<section class="page"><div class="pageHeader"><div><div class="sectionLabel">RALLYCROSS</div><h1>${race?esc(race.eventName):'Новое соревнование'}</h1><p>Настройка события. После запуска вся работа переходит в одноэкранный пульт.</p></div>${race&&race.stage!=='setup'?`<button class="btn primary" data-action="cockpit">Открыть пульт</button>`:''}</div>
 <div class="setupShell"><aside class="card setupSide"><div class="step ${!race||step==='setup'?'active':'done'}">1 · Событие</div><div class="step ${race&&step==='setup'?'active':race?'done':''}">2 · Пилоты</div><div class="step ${race&&step==='setup'?'active':race?'done':''}">3 · Формат</div><div class="step ${race&&step!=='setup'?'active':''}">4 · Пульт гонки</div></aside>
 <div class="grid">
  <article class="card"><div class="sectionLabel">СОБЫТИЕ</div><h2>Основные данные</h2><div class="formGrid">
   <div class="field"><label>Название</label><input id="raceName" value="${esc(race?.eventName||'Legion RX Cup')}" ${race&&race.stage!=='setup'?'disabled':''}></div>
   <div class="field"><label>Дата</label><input id="raceDate" type="date" value="${esc(race?.eventDate||new Date().toISOString().slice(0,10))}" ${race&&race.stage!=='setup'?'disabled':''}></div>
   <div class="field"><label>Место</label><input id="raceLocation" value="${esc(race?.eventLocation||'')}" placeholder="Трасса / город" ${race&&race.stage!=='setup'?'disabled':''}></div>
   <div class="field"><label>Чемпионат</label><select id="raceChamp" ${race&&race.stage!=='setup'?'disabled':''}><option value="">Клубная гонка</option>${state.championships.map(c=>`<option value="${c.id}" ${race?.championshipId===c.id?'selected':''}>${esc(c.name)} · ${esc(c.season)}</option>`).join('')}</select></div>
  </div>${!race?`<div class="btnRow" style="margin-top:14px"><button class="btn primary" data-action="create-race">Создать событие</button></div>`:''}</article>
  ${race?pilotSetupCard(race):''}
  ${race?formatSetupCard(race):''}
 </div></div></section>`;
}
function pilotSetupCard(race){return `<article class="card"><div class="pageHeader" style="margin:0 0 12px"><div><div class="sectionLabel">ПИЛОТЫ</div><h2>Участники · ${race.pilots.length}</h2></div>${race.stage==='setup'?`<div class="btnRow"><button class="btn secondary" data-action="add-db-pilot">Из базы</button><button class="btn primary" data-action="quick-pilot">＋ Новый</button></div>`:''}</div><div class="list">${race.pilots.length?race.pilots.map((p,i)=>`<div class="listRow"><div class="avatar">${nameInitials(p.name)}</div><div class="grow"><div class="name">${i+1}. ${esc(p.name)}</div><div class="sub">${esc(p.club||'Без клуба')} · транспондер ${esc(p.transponder||'не назначен')}</div></div>${race.stage==='setup'?`<button class="btn secondary" data-remove-race-pilot="${p.id}">Убрать</button>`:''}</div>`).join(''):`<div class="empty">Добавьте минимум двух пилотов.</div>`}</div></article>`;}
function formatSetupCard(race){return `<article class="card"><div class="sectionLabel">ФОРМАТ</div><h2>Параметры RallyCross</h2><div class="formGrid"><div class="field"><label>Квалификационных серий</label><select id="qCount" ${race.stage!=='setup'?'disabled':''}>${[3,4,5].map(n=>`<option ${race.qualifyingCount===n?'selected':''}>${n}</option>`).join('')}</select></div><div class="field"><label>Квалификация, минут</label><input id="qMinutes" type="number" min="1" max="30" value="${race.raceSettings?.qualificationMinutes||state.settings.qualificationMinutes}" ${race.stage!=='setup'?'disabled':''}></div><div class="field"><label>Финал, кругов</label><input id="finalLaps" type="number" min="1" max="99" value="${race.raceSettings?.finalLaps||state.settings.finalLaps}" ${race.stage!=='setup'?'disabled':''}></div><div class="field"><label>Минимальный круг LapWiz, сек</label><input id="minLap" type="number" min="1" max="60" value="${race.raceSettings?.minLapSec||state.settings.minLapSec}" ${race.stage!=='setup'?'disabled':''}></div></div>${race.stage==='setup'?`<div class="btnRow" style="margin-top:14px"><button class="btn primary" data-action="prepare-race" ${race.pilots.length<2?'disabled':''}>Сформировать заезды и открыть пульт</button><button class="btn danger" data-action="delete-race">Удалить событие</button></div>`:`<p>Формат зафиксирован. Изменение структуры после старта отключено, чтобы не разрушить результаты.</p>`}</article>`;}

function cockpitView(){
 if(!state.race||state.race.stage==='setup')return `<section class="page"><div class="card"><h2>Соревнование ещё не подготовлено</h2><button class="btn primary" data-action="open-rx">К настройке</button></div></section>`;
 const race=state.race,ev=currentEvent(race),events=eventList(race),session=ensureSession(ev),pilots=ev?liveRanking(getEventPilots(race,ev),session):[];const done=race.stage==='finished',tie=race.stage==='tie';
 return `<section class="cockpit">
 <aside class="eventRail ${state.mobileEvents?'open':''}" id="eventRail"><div class="eventRailHead"><div><div class="sectionLabel">СОБЫТИЯ</div><b>Ход соревнования</b></div><button class="iconBtn mobileTools" data-action="close-events">×</button></div><div class="eventRailList">${events.map((e,i)=>eventItem(race,e,i)).join('')}${tie?`<div class="eventItem current"><div class="top"><b>🎲 Жеребьёвка</b><span class="eventDot"></span></div><small>Абсолютное равенство после квалификации</small></div>`:''}${done?`<div class="eventItem completed"><div class="top"><b>🏆 Итоговый протокол</b><span class="eventDot"></span></div><small>Соревнование завершено</small></div>`:''}</div></aside>
 <div class="cockpitMain">
  <div class="raceState"><div><div class="mobileTools"><button class="btn secondary" data-action="toggle-events">События</button><button class="btn secondary" data-action="toggle-widgets">Виджеты</button></div><div class="stateTitle"><span class="badge">${done?'ФИНИШ':tie?'ЖЕРЕБЬЁВКА':session?.phase==='running'?'LIVE':session?.phase==='countdown'?'ОТСЧЁТ':'ГОТОВНОСТЬ'}</span><h2>${done?'Соревнование завершено':tie?'Нужно разрешить абсолютное равенство':esc(ev?.label||'Нет активного заезда')}</h2></div><div class="stateMeta">${done?'Откройте итоговую таблицу справа.':tie?'Сохраняем спортивную логику v3.4: перед финалами требуется жеребьёвка равных пилотов.':eventRuleText(race,ev)}</div></div><div><div class="timerCaption">${timerCaption(session,ev)}</div><div id="mainTimer" class="bigTimer">${done||tie?'00:00':displayTimer(session,ev)}</div></div></div>
  <div class="pilotBoard"><div class="pilotBoardHead"><div><div class="sectionLabel">ТЕКУЩИЙ ЗАЕЗД</div><h3>${done?'Итог соревнования':tie?'Квалификационный рейтинг':`${pilots.length} пилотов`}</h3></div><div class="btnRow"><button class="btn secondary" data-action="race-results">Таблицы</button><button class="btn secondary" data-action="toggle-results">${state.resultsOpen?'Скрыть текущий':'Текущий результат'}</button></div></div>
   <div class="pilotBoardTable">${done?finalProtocolTable(race):tie?qualifyingStandingsTable(race):pilotTable(pilots,session)}</div>
  </div>
 </div>
 <aside class="widgetStack ${state.mobileWidgets?'open':''}" id="widgetStack"><div class="mobileTools" style="justify-content:flex-end"><button class="btn secondary" data-action="close-widgets">Закрыть</button></div>
  ${tie?tieWidget(race):resultsWidget(race,ev,pilots,session)}
  ${lapwizWidget()}
  <div class="widget disabled"><div class="widgetHead"><h3>${uiIcon('calendar','widgetIcon')} Расписание / автоматизация</h3><span class="badge soon">СКОРО</span></div><div class="widgetContent">Запуск по времени, предупреждения 10/3/1 мин, сдвиг расписания.</div></div>
  <div class="widget disabled"><div class="widgetHead"><h3>${uiIcon('mic','widgetIcon')} Диктор</h3><span class="badge soon">СКОРО</span></div><div class="widgetContent">Отсчёт, позиции, финиш и переход к следующему заезду.</div></div>
  <div class="widget disabled"><div class="widgetHead"><h3>${uiIcon('monitor','widgetIcon')} Broadcast / OBS</h3><span class="badge soon">СКОРО</span></div><div class="widgetContent">Телевизионная графика и прямая трансляция.</div></div>
 </aside>
 <div class="controlBar">${controlButtons(done,session,tie)}</div>
 </section>`;
}
function eventItem(race,e,i){const s=eventStatus(race,e),pilots=(e.pilots||[]).length;return `<div class="eventItem ${s}" ${s==='completed'?`data-show-event="${e.key}" style="cursor:pointer"`:''}><div class="top"><b>${i+1}. ${esc(e.label)}</b><span class="eventDot"></span></div><small>${pilots} пилотов · ${s==='completed'?'завершён · нажмите для результата':s==='current'?'текущий':s==='ready'?'готов':'закрыт'}</small></div>`;}
function eventRuleText(race,ev){if(!ev)return'Нет активного события';const r=eventRule(race,ev);return r.limitType==='time'?`По времени · ${r.durationMin} мин · финиш текущего круга`:`По кругам · ${r.targetLaps} кругов`;}
function timerCaption(s,ev){if(!ev)return'ГОТОВО';if(s?.phase==='countdown')return'ДО СТАРТА';if(s?.phase==='running')return eventRule(state.race,ev).limitType==='time'?'ДО ФИНИША':'ВРЕМЯ ЗАЕЗДА';if(s?.phase==='finished')return'ЗАЕЗД ОСТАНОВЛЕН';return'ГОТОВНОСТЬ';}
function displayTimer(s,ev){if(!ev)return'00:00';if(!s)return'00:00';if(s.phase==='countdown')return `00:${String(Math.max(0,s.countdownLeft||0)).padStart(2,'0')}`;const r=eventRule(state.race,ev),elapsed=sessionElapsed(s);if(r.limitType==='time')return fmtClock(r.durationMin*60000-elapsed);return fmtClock(elapsed);}
function pilotTable(pilots,session){return `<div class="pilotRow header"><span>POS</span><span>Пилот</span><span>Круги</span><span>Лучший</span><span>Последний</span><span>Отставание</span><span>Ручн.</span></div>${pilots.map((p,i)=>{const l=session?.live?.[p.id]||blankLive();const gap=gapText(pilots,session,p,i);return `<div class="pilotRow ${i===0&&l.laps>0?'leader':''} ${l.finished?'finished':''}" data-pilot-row="${p.id}"><div class="pos">${i+1}</div><div><div class="name">${esc(p.name)}</div><div class="sub">ID ${esc(p.transponder||'—')} ${l.finished?'· Финиш':''}</div></div><b>${l.laps}</b><span>${fmtMs(l.bestLapMs)}</span><span>${fmtMs(l.lastLapMs)}</span><span>${gap}</span><button class="lapButton" data-manual-pass="${p.id}" ${session?.phase!=='running'&&session?.phase!=='finishing'?'disabled':''}>＋1</button></div>`;}).join('')}`;}
function blankLive(){return{laps:0,bestLapMs:Infinity,lastLapMs:null,lastPassPerf:null,lastDeviceTicks:null,elapsedMs:0,finished:false,finishedAt:null,status:'READY'};}
function liveRanking(pilots,session){if(!session)return pilots;return [...pilots].sort((a,b)=>{const A=session.live?.[a.id]||blankLive(),B=session.live?.[b.id]||blankLive();if(B.laps!==A.laps)return B.laps-A.laps;if(A.finished!==B.finished)return A.finished?-1:1;return (A.elapsedMs||Infinity)-(B.elapsedMs||Infinity)||(a.registrationOrder||999)-(b.registrationOrder||999);});}
function gapText(ranked,session,p,index){if(!session||index===0)return index===0?'Лидер':'—';const leader=session.live?.[ranked[0].id]||blankLive(),r=session.live?.[p.id]||blankLive();if(leader.laps-r.laps>0)return `+${leader.laps-r.laps} кр.`;if(r.elapsedMs&&leader.elapsedMs)return `+${fmtMs(Math.max(0,r.elapsedMs-leader.elapsedMs))}`;return'—';}
function resultsWidget(race,ev,pilots,session){if(race.stage==='finished')return `<div class="widget resultsWidget"><div class="widgetHead"><h3>${uiIcon('trophy','widgetIcon')} Итог</h3><span class="badge">ГОТОВО</span></div><div class="widgetContent">${compactFinalProtocol(race)}</div></div>`;if(!ev)return'';const draft=makeDraftResult(pilots,session);return `<div class="widget resultsWidget"><div class="widgetHead"><h3>${uiIcon('chart','widgetIcon')} Результаты заезда</h3><button class="btn secondary" data-action="toggle-results">${state.resultsOpen?'Свернуть':'Развернуть'}</button></div><div class="widgetContent drawerResults ${state.resultsOpen?'open':''}" id="resultDrawer">${draft.map((x,i)=>`<div class="resultEditRow"><div><b>${i+1}. ${esc(x.name)}</b><div class="sub">${x.laps} кр. · ${fmtMs(x.elapsedMs)}</div></div><select data-result-status="${x.pilotId}"><option value="FIN" ${x.status==='FIN'?'selected':''}>FIN</option><option value="DNF">DNF</option><option value="DNS">DNS</option><option value="DSQ">DSQ</option></select><input type="number" min="1" value="${i+1}" data-result-place="${x.pilotId}"></div>`).join('')}<div class="btnRow" style="margin-top:10px"><button class="btn good" data-action="save-event-result" ${session?.phase!=='finished'?'disabled':''}>Сохранить и перейти дальше</button></div></div>${!state.resultsOpen?`<div class="widgetContent">Таблица раскрывается после заезда. Сейчас: ${draft.slice(0,3).map((x,i)=>`${i+1}. ${esc(x.name)}`).join(' · ')||'нет данных'}</div>`:''}</div>`;}
function lapwizWidget(){return `<div class="widget"><div class="widgetHead"><h3>${uiIcon('bluetooth','widgetIcon')} LapWiz Core</h3><span class="badge ${lapwiz.connected?'':'soon'}">${lapwiz.connected?'ПОДКЛЮЧЁН':'OFFLINE'}</span></div><div class="widgetContent"><div>Устройство: <strong>${esc(lapwiz.device?.name||'—')}</strong></div><div>Режим: <strong>${lapwiz.running?'RUNNING':'STOPPED'}</strong></div><div>Звук прохода: <strong>${state.settings.lapSound?'ВКЛ':'ВЫКЛ'}</strong></div><div class="btnRow" style="margin-top:10px">${lapwiz.connected?`<button class="btn secondary" data-action="lap-disconnect">Отключить</button>`:`<button class="btn primary" data-action="lap-connect">Подключить</button>`}</div></div></div>`;}
function controlButtons(done,s,tie=false){if(tie)return `<button class="btn secondary" data-action="toggle-results">Таблица</button><button class="btn secondary" disabled>ПАУЗА</button><button class="btn secondary" disabled>+1 МИН</button><button class="btn primary" data-action="tie-draw">🎲 ЖЕРЕБЬЁВКА</button><button class="btn secondary" disabled>РЕЗУЛЬТАТЫ</button><button class="btn danger" data-action="home">ВЫХОД</button>`;if(done)return `<button class="btn secondary" data-action="home">Главная</button><button class="btn secondary" data-action="open-rx">Настройка</button><button class="btn primary" data-action="race-results">Итоговая таблица</button><button class="btn secondary" disabled>Диктор</button><button class="btn secondary" disabled>Broadcast</button><button class="btn danger" data-action="archive-race">В архив</button>`;const p=s?.phase||'ready';return `<button class="btn secondary" disabled>ПАУЗА</button><button class="btn finishBtn" data-action="finish-session" ${!['running','finishing'].includes(p)?'disabled':''}>ФИНИШ</button><button class="btn secondary" disabled>+1 МИН</button><button class="btn startBtn" data-action="start-session" ${!['ready','finished'].includes(p)||p==='finished'?'disabled':''}>СТАРТ</button><button class="btn secondary" data-action="race-results">РЕЗУЛЬТАТЫ</button><button class="btn danger" data-action="stop-session" ${!['running','finishing','countdown'].includes(p)?'disabled':''}>СТОП</button>`;}

function qualifyingStandingsTable(race){updateStandings(race);return `<div class="pilotRow header"><span>POS</span><span>Пилот</span><span>Best 3</span><span>Q</span><span></span><span></span><span></span></div>${race.pilots.map((p,i)=>`<div class="pilotRow"><div class="pos">${i+1}</div><div class="name">${esc(p.name)}</div><b>${p.best3}</b><span style="grid-column:4/7">${(p.qualifying||[]).map(q=>q.status==='FIN'?`${q.place} (${q.points})`:q.status).join(' · ')}</span><span></span></div>`).join('')}`;}
function tieWidget(race){const groups=getExactTieGroups(race);return `<div class="widget resultsWidget"><div class="widgetHead"><h3>Жеребьёвка · абсолютное равенство</h3><span class="badge soon">ТРЕБУЕТ ДЕЙСТВИЯ</span></div><div class="widgetContent">${groups.map(g=>`<div style="padding:6px 0"><b>${g.map(p=>esc(p.name)).join(' · ')}</b></div>`).join('')}<button class="btn primary" data-action="tie-draw">Провести жеребьёвку и сформировать финалы</button></div></div>`;}

function finalProtocolTable(race){if(!race.finalProtocol?.length)return'<div class="empty">Финальный протокол ещё не сформирован.</div>';return `<div class="pilotRow header"><span>POS</span><span>Пилот</span><span>Очки</span><span>Источник</span><span></span><span></span><span></span></div>${race.finalProtocol.map(r=>{const p=getPilot(race,r.pilotId);return `<div class="pilotRow"><div class="pos">${r.place}</div><div class="name">${esc(p?.name||'—')}</div><b>${r.eventPoints}</b><span style="grid-column:4/7">${esc(r.source)} ${r.status!=='FIN'?`· ${r.status}`:''}</span><span></span></div>`;}).join('')}`;}
function compactFinalProtocol(race){return race.finalProtocol.slice(0,10).map(r=>`<div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid var(--line)"><span>${r.place}. ${esc(getPilot(race,r.pilotId)?.name||'—')}</span><b>${r.eventPoints}</b></div>`).join('');}

function ensureSession(ev){if(!ev)return null;if(state.session?.eventKey!==ev.key){state.session={eventKey:ev.key,phase:'ready',startedAtPerf:null,startedAtEpoch:null,finishedAtEpoch:null,countdownLeft:state.race.raceSettings.countdownSec,live:Object.fromEntries(getEventPilots(state.race,ev).map(p=>[p.id,blankLive()])),unknown:{},lastPass:''};}return state.session;}
function sessionElapsed(s){if(!s?.startedAtPerf)return 0;if(s.finishedAtEpoch&&s.startedAtEpoch)return s.finishedAtEpoch-s.startedAtEpoch;return performance.now()-s.startedAtPerf;}
function startTicker(){if(state.sessionTick)clearInterval(state.sessionTick);state.sessionTick=setInterval(()=>{if(state.view!=='cockpit')return;updateDynamicCockpit();checkSessionLimit();},120);}
function updateDynamicCockpit(){const timer=$('#mainTimer');if(timer){const ev=currentEvent(state.race);timer.textContent=displayTimer(state.session,ev);}const board=$('.pilotBoardTable');const ev=currentEvent(state.race);if(board&&ev&&state.session&&state.session.phase!=='finished'){const ranked=liveRanking(getEventPilots(state.race,ev),state.session);board.innerHTML=pilotTable(ranked,state.session);bindManualPasses();}}
async function beginCountdown(){const ev=currentEvent(state.race),s=ensureSession(ev);if(!ev||s.phase!=='ready')return;s.phase='countdown';s.countdownLeft=state.race.raceSettings.countdownSec;render();state.countdownTick=setInterval(async()=>{s.countdownLeft--;if(s.countdownLeft<=0){clearInterval(state.countdownTick);state.countdownTick=null;await beginRaceNow();}else updateDynamicCockpit();},1000);}
async function beginRaceNow(){const ev=currentEvent(state.race),s=ensureSession(ev),rule=eventRule(state.race,ev);try{if(lapwiz.connected)await lapwiz.start(rule);}catch(e){toast(`LapWiz START: ${e.message}`);return;}s.phase='running';s.startedAtPerf=performance.now();s.startedAtEpoch=Date.now();s.finishedAtEpoch=null;s.timeExpired=false;Object.values(s.live).forEach(v=>Object.assign(v,blankLive()));logEvent(`Старт: ${ev.label}`);startTicker();render();}
async function finishSession(reason='Финиш судьёй'){const s=state.session;if(!s)return;if(lapwiz.connected&&lapwiz.running){try{await lapwiz.stop();}catch(e){toast(`STOP: ${e.message}`);}}s.phase='finished';s.finishedAtEpoch=Date.now();logEvent(reason);state.resultsOpen=true;render();}
async function stopSession(){if(state.countdownTick){clearInterval(state.countdownTick);state.countdownTick=null;}await finishSession('Аварийный STOP');}
function checkSessionLimit(){const ev=currentEvent(state.race),s=state.session;if(!ev||!s||s.phase!=='running')return;const r=eventRule(state.race,ev),elapsed=sessionElapsed(s);if(r.limitType==='time'&&elapsed>=r.durationMin*60000&&!s.timeExpired){s.timeExpired=true;s.phase='finishing';Object.values(s.live).forEach(v=>{if(!v.finished)v.needsFinish=true;});toast('Время истекло — финиш на следующем проходе');}if(r.limitType==='laps'){const all=Object.values(s.live).every(v=>v.finished);if(all)finishSession('Все пилоты финишировали');}}
function processPass(transponder,deviceMs=null,source='MANUAL'){const ev=currentEvent(state.race),s=state.session;if(!ev||!s||!['running','finishing'].includes(s.phase))return;const p=getEventPilots(state.race,ev).find(x=>String(x.transponder)===String(transponder));if(!p){s.unknown[transponder]=(s.unknown[transponder]||0)+1;if(source==='LAPWIZ')lapwiz.unknownBeep();toast(`Неизвестный ID ${transponder}`);return;}if(source==='LAPWIZ'&&state.settings.lapSound)lapwiz.beep(true);processPilotPass(p,deviceMs,source);}
function processPilotPass(p,deviceMs=null,source='MANUAL'){const ev=currentEvent(state.race),s=state.session;if(!ev||!s||!['running','finishing'].includes(s.phase))return;const l=s.live[p.id]||blankLive();if(l.finished)return;const now=performance.now();let lapMs=null;if(Number.isFinite(deviceMs)){if(Number.isFinite(l.lastDeviceMs)&&deviceMs>l.lastDeviceMs)lapMs=deviceMs-l.lastDeviceMs;else if(!l.lastDeviceMs&&deviceMs>0)lapMs=deviceMs;l.lastDeviceMs=deviceMs;}if(!Number.isFinite(lapMs)||lapMs<=0)lapMs=now-(l.lastPassPerf??s.startedAtPerf);l.lastPassPerf=now;l.lastLapMs=lapMs;l.bestLapMs=Math.min(l.bestLapMs,lapMs);l.laps++;l.elapsedMs=Number.isFinite(deviceMs)&&deviceMs>0?deviceMs:now-s.startedAtPerf;const rule=eventRule(state.race,ev);if(rule.limitType==='laps'&&l.laps>=rule.targetLaps){l.finished=true;l.finishedAt=l.elapsedMs;}if(s.phase==='finishing'&&s.timeExpired){l.finished=true;l.finishedAt=l.elapsedMs;}s.live[p.id]=l;s.lastPass=`${p.name} · ${l.laps} · ${fmtMs(lapMs)}`;if(source==='MANUAL'&&state.settings.lapSound)lapwiz.beep(true);updateDynamicCockpit();if(Object.values(s.live).every(v=>v.finished)&&(rule.limitType==='laps'||s.phase==='finishing'))finishSession('Все пилоты завершили заезд');}
function logEvent(text){state.race.runtime.eventLog.push({time:new Date().toISOString(),text});persistRace();}
function makeDraftResult(pilots,session){return pilots.map((p,i)=>{const l=session?.live?.[p.id]||blankLive();return{pilotId:p.id,name:p.name,status:'FIN',place:i+1,laps:l.laps,elapsedMs:l.elapsedMs};});}
function readEditedResult(){const ev=currentEvent(state.race),ranked=liveRanking(getEventPilots(state.race,ev),state.session);return ranked.map((p,i)=>{const st=document.querySelector(`[data-result-status="${CSS.escape(String(p.id))}"]`)?.value||'FIN',place=Number(document.querySelector(`[data-result-place="${CSS.escape(String(p.id))}"]`)?.value||i+1);return{pilotId:p.id,status:st,place:st==='FIN'?place:null,dnfOrder:st==='DNF'?i+1:null};});}
function saveCurrentEventResult(){const race=state.race,ev=currentEvent(race),s=state.session;if(!ev||s?.phase!=='finished')return toast('Сначала завершите заезд');try{const result=readEditedResult();if(ev.type==='qualifying')saveQualifyingEvent(race,ev.key,result);else saveFinalEvent(race,ev.key,result);syncChampionshipIfFinished(race);persistRace();state.session=null;state.resultsOpen=false;toast('Результат сохранён. Следующий заезд подготовлен.');render();}catch(e){toast(e.message);}}

function championshipsView(){return `<section class="page"><div class="pageHeader"><div><div class="sectionLabel">СЕЗОНЫ</div><h1>Чемпионаты</h1><p>Отдельный общий раздел Legion RX. Этапы получают итоговые очки из завершённых RallyCross-соревнований.</p></div><button class="btn primary" data-action="new-champ">＋ Чемпионат</button></div><div class="grid grid2">${state.championships.length?state.championships.map(c=>champCard(c)).join(''):`<div class="card empty">Пока нет чемпионатов.</div>`}</div></section>`;}
function champCard(c){const standings=champStandings(c);return `<article class="card"><div class="sectionLabel">${esc(c.season)}</div><h2>${esc(c.name)}</h2><p>${c.stages.length} этапов · план ${c.stagesPlanned}</p>${standings.length?`<div class="tableWrap"><table class="table"><thead><tr><th>Место</th><th>Пилот</th><th>Очки</th></tr></thead><tbody>${standings.slice(0,10).map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td><td><b>${r.total}</b></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Нет завершённых этапов.</div>`}</article>`;}
function champStandings(c){const m=new Map();(c.stages||[]).forEach(s=>(s.results||[]).forEach(r=>{const row=m.get(r.driverId)||{driverId:r.driverId,name:r.name,total:0};row.total+=Number(r.points||0);m.set(r.driverId,row);}));return[...m.values()].sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name));}
function syncChampionshipIfFinished(race){if(race.stage!=='finished'||!race.championshipId)return;const c=state.championships.find(x=>x.id===race.championshipId);if(!c)return;const stageNo=Number(race.championshipStageNumber)||((c.stages?.length||0)+1),results=race.finalProtocol.map(r=>{const p=getPilot(race,r.pilotId);return{driverId:p.profileId||p.id,name:p.name,place:r.place,points:r.eventPoints,status:r.status};});const stage={number:stageNo,raceId:race.id,name:race.eventName,date:race.eventDate,results};const idx=c.stages.findIndex(s=>s.raceId===race.id||s.number===stageNo);if(idx>=0)c.stages[idx]=stage;else c.stages.push(stage);save(KEYS.champ,state.championships);}

function pilotsView(){return `<section class="page"><div class="pageHeader"><div><div class="sectionLabel">ОБЩАЯ БАЗА</div><h1>Пилоты</h1><p>Профиль используется в соревнованиях; транспондер хранится здесь и переносится в состав гонки.</p></div><button class="btn primary" data-action="new-db-pilot">＋ Пилот</button></div><div class="card"><div class="list">${state.pilotDb.length?state.pilotDb.map(p=>`<div class="listRow"><div class="avatar">${nameInitials(p.name)}</div><div class="grow"><div class="name">${esc(p.name)}</div><div class="sub">${esc(p.club||'Без клуба')} · ID транспондера ${esc(p.transponder||'—')}</div></div><button class="btn secondary" data-edit-pilot="${p.id}">Изменить</button><button class="btn danger" data-delete-pilot="${p.id}">Удалить</button></div>`).join(''):`<div class="empty">Создайте первый профиль пилота.</div>`}</div></div></section>`;}

function settingsView(){return `<section class="page"><div class="pageHeader"><div><div class="sectionLabel">СИСТЕМА</div><h1>Настройки</h1><p>Оболочка меняется отдельно от спортивной логики.</p></div></div><div class="settingsGrid">
 <article class="card settingGroup"><h3>${uiIcon('settings','widgetIcon')} Интерфейс</h3><div class="toggleRow"><span>Тёмная тема</span><input class="toggle" id="darkToggle" type="checkbox" ${state.settings.theme==='dark'?'checked':''}></div><div class="field" style="margin-top:12px"><label>Язык интерфейса</label><select id="langSelect"><option value="ru" ${state.settings.lang==='ru'?'selected':''}>Русский</option><option value="en" ${state.settings.lang==='en'?'selected':''}>English</option></select></div><p>English mode translates the main shell, controls and settings. Sport-specific result abbreviations FIN/DNF/DNS/DSQ remain universal.</p></article>

 <article class="card settingGroup designLabCard"><h3>${uiIcon('settings','widgetIcon')} Design Lab</h3><p>Живая настройка геометрии интерфейса без правки CSS: радиусы, отступы, высота кнопок, ширина контента и сетка карточек.</p><div class="designLabSample"><span></span><span></span><span></span></div><button class="btn primary" data-action="open-design-lab">Открыть Design Lab</button></article>
 <article class="card settingGroup"><h3>${uiIcon('bluetooth','widgetIcon')} LapWiz</h3><div class="toggleRow"><span>Звук прохода</span><input class="toggle" id="soundToggle" type="checkbox" ${state.settings.lapSound?'checked':''}></div><div class="field" style="margin-top:12px"><label>Минимальное время круга, сек</label><input id="settingsMinLap" type="number" min="1" max="60" value="${state.settings.minLapSec}"></div><div class="btnRow" style="margin-top:12px">${lapwiz.connected?`<button class="btn secondary" data-action="lap-disconnect">Отключить LapWiz</button>`:`<button class="btn primary" data-action="lap-connect">Подключить LapWiz</button>`}</div><p>BLE: FFF0 / команды FFF3 / уведомления FFF4. Android Chrome + HTTPS.</p></article>
 <article class="card settingGroup"><h3>${uiIcon('flag','widgetIcon')} Значения по умолчанию</h3><div class="formGrid"><div class="field"><label>Квалификация, мин</label><input id="settingsQMin" type="number" value="${state.settings.qualificationMinutes}"></div><div class="field"><label>Финал, кругов</label><input id="settingsFLaps" type="number" value="${state.settings.finalLaps}"></div><div class="field"><label>Отсчёт, сек</label><input id="settingsCountdown" type="number" value="${state.settings.countdownSec}"></div></div><button class="btn primary" style="margin-top:12px" data-action="save-settings">Сохранить</button></article>
 <article class="card settingGroup"><h3>О приложении</h3><p><b>Legion RX 4.0.4 Alpha</b></p><p>Новая мультисистемная оболочка. RallyCross-движок перенесён из Championship Edition v3.4. LapWiz Core основан на протестированном протоколе v0.5 Sound.</p><div class="list"><div class="listRow"><div class="grow"><b>Ралли-спринт</b><div class="sub">модуль ещё не реализован</div></div><span class="badge soon">СКОРО</span></div><div class="listRow"><div class="grow"><b>Classic RC</b><div class="sub">модуль ещё не реализован</div></div><span class="badge soon">СКОРО</span></div><div class="listRow"><div class="grow"><b>Автоматизация / диктор / Broadcast</b><div class="sub">архитектурно зарезервировано</div></div><span class="badge soon">СКОРО</span></div></div></article>
 </div></section>`;}

function bindView(){
 $$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
 $$('[data-action]').forEach(b=>b.addEventListener('click',()=>handleAction(b.dataset.action,b)));
 $$('[data-remove-race-pilot]').forEach(b=>b.addEventListener('click',()=>{if(state.race.stage!=='setup')return;state.race.pilots=state.race.pilots.filter(p=>p.id!==b.dataset.removeRacePilot);state.race.pilots.forEach((p,i)=>p.registrationOrder=i+1);persistRace();render();}));
 $$('[data-edit-pilot]').forEach(b=>b.addEventListener('click',()=>pilotModal(state.pilotDb.find(p=>p.id===b.dataset.editPilot))));
 $$('[data-delete-pilot]').forEach(b=>b.addEventListener('click',()=>{if(confirm('Удалить профиль из базы?')){state.pilotDb=state.pilotDb.filter(p=>p.id!==b.dataset.deletePilot);save(KEYS.pilots,state.pilotDb);render();}}));
 $$('[data-show-event]').forEach(b=>b.addEventListener('click',()=>raceResultsModal(b.dataset.showEvent)));
 bindManualPasses();
}
function bindManualPasses(){$$('[data-manual-pass]').forEach(b=>b.onclick=()=>{const p=getPilot(state.race,b.dataset.manualPass);if(p)processPilotPass(p,null,'MANUAL');});}
async function handleAction(action){
 if(action==='home')return nav('home');if(action==='open-rx'||action==='open-current')return nav(state.race?.stage&&state.race.stage!=='setup'?'cockpit':'rallySetup');if(action==='cockpit')return nav('cockpit');
 if(action==='create-race'){const input={eventName:$('#raceName').value.trim()||'Legion RX Cup',eventDate:$('#raceDate').value,eventLocation:$('#raceLocation').value.trim(),championshipId:$('#raceChamp').value,qualificationMinutes:state.settings.qualificationMinutes,finalLaps:state.settings.finalLaps,minLapSec:state.settings.minLapSec,countdownSec:state.settings.countdownSec};state.race=makeRace(input);if(input.championshipId){const c=state.championships.find(x=>x.id===input.championshipId);state.race.championshipStageNumber=(c?.stages?.reduce((m,s)=>Math.max(m,s.number||0),0)||0)+1;}persistRace();return render();}
 if(action==='quick-pilot')return pilotModal(null,true);if(action==='add-db-pilot')return pilotPicker();
 if(action==='prepare-race'){if(state.race.pilots.length<2)return toast('Нужно минимум два пилота');state.race.eventName=$('#raceName').value.trim()||state.race.eventName;state.race.eventDate=$('#raceDate').value;state.race.eventLocation=$('#raceLocation').value.trim();state.race.championshipId=$('#raceChamp').value;state.race.qualifyingCount=Number($('#qCount').value);state.race.raceSettings={qualificationMinutes:Number($('#qMinutes').value)||5,finalLaps:Number($('#finalLaps').value)||7,minLapSec:Number($('#minLap').value)||2,countdownSec:state.settings.countdownSec};prepareRace(state.race);persistRace();state.session=null;return nav('cockpit');}
 if(action==='delete-race'){if(confirm('Удалить текущее соревнование?')){state.race=null;save(KEYS.race,null);nav('home');}return;}
 if(action==='toggle-events'){state.mobileEvents=true;return render();}if(action==='close-events'){state.mobileEvents=false;return render();}if(action==='toggle-widgets'){state.mobileWidgets=true;return render();}if(action==='close-widgets'){state.mobileWidgets=false;return render();}
 if(action==='race-results')return raceResultsModal();
 if(action==='tie-draw'){resolveQualificationTie(state.race);persistRace();state.session=null;toast('Жеребьёвка проведена. Финалы сформированы.');return render();}
 if(action==='toggle-results'){state.resultsOpen=!state.resultsOpen;return render();}if(action==='start-session')return beginCountdown();if(action==='finish-session')return finishSession();if(action==='stop-session')return stopSession();if(action==='save-event-result')return saveCurrentEventResult();
 if(action==='lap-connect'){try{lapwiz.ensureAudio();await lapwiz.connect();toast('LapWiz подключён');updateHeader();render();}catch(e){toast(e.message);}return;}if(action==='lap-disconnect'){await lapwiz.disconnect();toast('LapWiz отключён');updateHeader();render();return;}
 if(action==='new-db-pilot')return pilotModal();if(action==='new-champ')return championshipModal();if(action==='open-design-lab')return openDesignLab();
 if(action==='save-settings'){state.settings.theme=$('#darkToggle')?.checked?'dark':'light';state.settings.lang=$('#langSelect')?.value||'ru';state.settings.lapSound=Boolean($('#soundToggle')?.checked);state.settings.minLapSec=Number($('#settingsMinLap')?.value)||2;state.settings.qualificationMinutes=Number($('#settingsQMin')?.value)||5;state.settings.finalLaps=Number($('#settingsFLaps')?.value)||7;state.settings.countdownSec=Number($('#settingsCountdown')?.value)||5;save(KEYS.settings,state.settings);applySettings();toast('Настройки сохранены');return render();}
 if(action==='archive-race'){archiveCurrentRace();return;}
}


function openDesignLab(){
 const ui={...state.settings.ui};
 const controls=[
  ['cardRadius','Карточки','px',0,32],['tileRadius','Карточки дисциплин','px',0,32],['buttonRadius','Кнопки','px',0,28],['inputRadius','Поля','px',0,24],
  ['iconRadius','Иконки / плашки','px',0,24],['heroRadius','Главный баннер','px',0,36],['widgetRadius','Виджеты пульта','px',0,28],['modalRadius','Окна','px',0,30],
  ['cardPadding','Внутренний отступ карточек','px',10,32],['sectionGap','Расстояние между блоками','px',6,28],['buttonHeight','Высота кнопок пульта','px',40,70],['contentWidth','Ширина контента на ПК','px',900,1600]
 ];
 $('#modalHost').innerHTML=`<div class="designBackdrop" id="designBackdrop"><aside class="designDrawer"><div class="designHead"><div><div class="sectionLabel">LIVE UI EDITOR</div><h2>Design Lab</h2><p>Крути значения — Legion RX меняется сразу.</p></div><button class="iconBtn" id="closeDesignLab">×</button></div>
 <div class="designScroll"><section class="designSection"><h3>Радиусы и размеры</h3>${controls.map(([key,label,unit,min,max])=>`<label class="rangeRow"><span><b>${label}</b><output id="out_${key}">${ui[key]}${unit}</output></span><input type="range" min="${min}" max="${max}" step="1" value="${ui[key]}" data-ui-token="${key}"></label>`).join('')}</section>
 <section class="designSection"><h3>Главная страница</h3><label class="field"><span>Карточек дисциплин в ряд</span><select id="designCols"><option value="3" ${ui.disciplineCols===3?'selected':''}>3 — широко</option><option value="2" ${ui.disciplineCols===2?'selected':''}>2 — крупнее</option><option value="1" ${ui.disciplineCols===1?'selected':''}>1 — вертикально</option></select></label></section>
 <section class="designSection"><h3>Быстрые пресеты радиуса</h3><div class="presetRow"><button class="btn secondary" data-radius-preset="square">Строже</button><button class="btn secondary" data-radius-preset="medium">Средне</button><button class="btn secondary" data-radius-preset="soft">Мягко</button></div></section>
 </div><div class="designFooter"><button class="btn secondary" id="resetDesignLab">Сбросить</button><button class="btn secondary" id="copyDesignJson">Показать JSON</button><button class="btn primary" id="saveDesignLab">Сохранить</button></div></aside></div>`;
 const sync=()=>{applyUiTokens(ui);document.querySelectorAll('[data-ui-token]').forEach(inp=>{const out=$(`#out_${inp.dataset.uiToken}`);if(out)out.textContent=`${ui[inp.dataset.uiToken]}px`;});};
 $$('[data-ui-token]').forEach(inp=>inp.addEventListener('input',()=>{ui[inp.dataset.uiToken]=Number(inp.value);sync();}));
 $('#designCols').addEventListener('change',e=>{ui.disciplineCols=Number(e.target.value);sync();});
 $$('[data-radius-preset]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.radiusPreset,vals=p==='square'?{cardRadius:6,tileRadius:8,buttonRadius:6,inputRadius:6,iconRadius:8,heroRadius:10,widgetRadius:8,modalRadius:10}:p==='medium'?{cardRadius:14,tileRadius:14,buttonRadius:9,inputRadius:8,iconRadius:10,heroRadius:18,widgetRadius:12,modalRadius:14}:{cardRadius:22,tileRadius:24,buttonRadius:14,inputRadius:12,iconRadius:14,heroRadius:28,widgetRadius:18,modalRadius:22};Object.assign(ui,vals);$$('[data-ui-token]').forEach(inp=>{if(vals[inp.dataset.uiToken]!=null)inp.value=vals[inp.dataset.uiToken];});sync();}));
 $('#closeDesignLab').onclick=()=>{applyUiTokens(state.settings.ui);closeModal();};
 $('#resetDesignLab').onclick=()=>{Object.assign(ui,defaultUi);$$('[data-ui-token]').forEach(inp=>inp.value=ui[inp.dataset.uiToken]);$('#designCols').value=String(ui.disciplineCols);sync();};
 $('#saveDesignLab').onclick=()=>{state.settings.ui={...ui};save(KEYS.settings,state.settings);applyUiTokens();closeModal();toast('Дизайн сохранён');};
 $('#copyDesignJson').onclick=()=>{const text=JSON.stringify(ui,null,2);const w=window.open('','_blank','width=520,height=680');if(w){w.document.write(`<pre style="font:14px/1.5 monospace;white-space:pre-wrap;padding:20px">${esc(text)}</pre>`);w.document.close();}else toast('Разрешите всплывающее окно для JSON');};
 sync();
}


function raceResultsModal(focusKey=''){
 const race=state.race;if(!race)return;
 updateStandings(race);
 const completed=eventList(race).filter(e=>e.saved);
 const eventTables=completed.map(e=>{
   const rows=(e.result||[]).map((r,i)=>{const p=getPilot(race,r.pilotId);return `<tr><td>${r.status==='FIN'?(r.place||i+1):esc(r.status)}</td><td>${esc(p?.name||'—')}</td><td>${r.status==='DNF'&&r.dnfOrder?`DNF-${r.dnfOrder}`:'—'}</td></tr>`;}).join('');
   return `<details ${focusKey===e.key?'open':''} class="card" style="box-shadow:none;margin-bottom:8px"><summary style="cursor:pointer;font-weight:850">${esc(e.label)}</summary><div class="tableWrap" style="margin-top:10px"><table class="table"><thead><tr><th>Место</th><th>Пилот</th><th>Статус</th></tr></thead><tbody>${rows}</tbody></table></div></details>`;
 }).join('');
 const qrows=race.pilots.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.name)}</td>${Array.from({length:race.qualifyingCount},(_,k)=>{const q=p.qualifying.find(x=>x.round===k+1);return `<td>${q?q.status==='FIN'?`${q.place} (${q.points})`:esc(q.status):'—'}</td>`}).join('')}<td><b>${p.best3}</b></td></tr>`).join('');
 const main=race.finals?.length?buildMainStandings(race):[];
 const mainRows=main.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(getPilot(race,r.pilotId)?.name||'—')}</td>${r.scores.map(v=>`<td>${v??'—'}</td>`).join('')}<td><b>${r.total??'—'}</b></td></tr>`).join('');
 $('#modalHost').innerHTML=`<div class="modalBackdrop"><div class="modal" style="width:min(980px,100%)"><div class="modalHead"><div><div class="sectionLabel">РЕЗУЛЬТАТЫ</div><h2>${esc(race.eventName)}</h2></div><button class="iconBtn" id="closeModal">×</button></div>
 <h3>Квалификационный рейтинг</h3><div class="tableWrap"><table class="table"><thead><tr><th>POS</th><th>Пилот</th>${Array.from({length:race.qualifyingCount},(_,i)=>`<th>Q${i+1}</th>`).join('')}<th>Best 3</th></tr></thead><tbody>${qrows}</tbody></table></div>
 ${main.length?`<h3 style="margin-top:16px">Финал A</h3><div class="tableWrap"><table class="table"><thead><tr><th>POS</th><th>Пилот</th><th>A1</th><th>A2</th><th>A3</th><th>Лучшие 2</th></tr></thead><tbody>${mainRows}</tbody></table></div>`:''}
 <h3 style="margin-top:16px">Завершённые заезды</h3>${eventTables||'<div class="empty">Пока нет завершённых заездов.</div>'}
 ${race.finalProtocol?.length?`<h3 style="margin-top:16px">Итоговый протокол</h3><div class="tableWrap"><table class="table"><thead><tr><th>Место</th><th>Пилот</th><th>Очки этапа</th><th>Источник</th></tr></thead><tbody>${race.finalProtocol.map(r=>`<tr><td>${r.place}</td><td>${esc(getPilot(race,r.pilotId)?.name||'—')}</td><td>${r.eventPoints}</td><td>${esc(r.source)}</td></tr>`).join('')}</tbody></table></div>`:''}
 </div></div>`;$('#closeModal').onclick=closeModal;
}

function pilotModal(existing=null,addToRace=false){const id=existing?.id||uid('profile');$('#modalHost').innerHTML=`<div class="modalBackdrop"><div class="modal"><div class="modalHead"><div><div class="sectionLabel">ПИЛОТ</div><h2>${existing?'Редактировать':'Новый профиль'}</h2></div><button class="iconBtn" id="closeModal">×</button></div><div class="formGrid"><div class="field"><label>Фамилия Имя</label><input id="mName" value="${esc(existing?.name||'')}"></div><div class="field"><label>Клуб</label><input id="mClub" value="${esc(existing?.club||'')}"></div><div class="field"><label>Город</label><input id="mCity" value="${esc(existing?.city||'')}"></div><div class="field"><label>ID транспондера</label><input id="mTrans" inputmode="numeric" value="${esc(existing?.transponder||'')}"></div></div><div class="btnRow" style="margin-top:14px"><button class="btn primary" id="savePilotModal">Сохранить</button></div></div></div>`;$('#closeModal').onclick=closeModal;$('#savePilotModal').onclick=()=>{const name=$('#mName').value.trim();if(!name)return toast('Введите имя');const profile={id,name,club:$('#mClub').value.trim(),city:$('#mCity').value.trim(),transponder:$('#mTrans').value.trim(),photo:existing?.photo||''};const idx=state.pilotDb.findIndex(p=>p.id===id);if(idx>=0)state.pilotDb[idx]=profile;else state.pilotDb.push(profile);save(KEYS.pilots,state.pilotDb);if(addToRace&&state.race?.stage==='setup'&&!state.race.pilots.some(p=>p.profileId===id)){const p=makePilot({...profile,profileId:id},state.race.pilots.length+1);p.profileId=id;state.race.pilots.push(p);persistRace();}closeModal();render();};}
function pilotPicker(){const available=state.pilotDb.filter(p=>!state.race.pilots.some(r=>r.profileId===p.id));$('#modalHost').innerHTML=`<div class="modalBackdrop"><div class="modal"><div class="modalHead"><div><div class="sectionLabel">БАЗА</div><h2>Добавить пилотов</h2></div><button class="iconBtn" id="closeModal">×</button></div><div class="list">${available.length?available.map(p=>`<label class="listRow"><input type="checkbox" data-pick-pilot="${p.id}"><div class="avatar">${nameInitials(p.name)}</div><div class="grow"><div class="name">${esc(p.name)}</div><div class="sub">ID ${esc(p.transponder||'—')}</div></div></label>`).join(''):`<div class="empty">Все пилоты из базы уже добавлены.</div>`}</div><button class="btn primary" id="addPicked" style="margin-top:12px">Добавить выбранных</button></div></div>`;$('#closeModal').onclick=closeModal;$('#addPicked').onclick=()=>{$$('[data-pick-pilot]:checked').forEach(ch=>{const profile=state.pilotDb.find(p=>p.id===ch.dataset.pickPilot);if(profile){const p=makePilot({...profile,profileId:profile.id},state.race.pilots.length+1);p.profileId=profile.id;state.race.pilots.push(p);}});persistRace();closeModal();render();};}
function championshipModal(){$('#modalHost').innerHTML=`<div class="modalBackdrop"><div class="modal"><div class="modalHead"><h2>Новый чемпионат</h2><button class="iconBtn" id="closeModal">×</button></div><div class="formGrid"><div class="field"><label>Название</label><input id="cName" value="Legion RX Cup"></div><div class="field"><label>Сезон</label><input id="cSeason" type="number" value="${new Date().getFullYear()}"></div><div class="field"><label>План этапов</label><input id="cStages" type="number" value="6"></div></div><button class="btn primary" id="saveChamp" style="margin-top:12px">Создать</button></div></div>`;$('#closeModal').onclick=closeModal;$('#saveChamp').onclick=()=>{state.championships.push({id:uid('champ'),name:$('#cName').value.trim()||'Legion RX Cup',season:Number($('#cSeason').value),stagesPlanned:Number($('#cStages').value)||6,stages:[]});save(KEYS.champ,state.championships);closeModal();render();};}
function closeModal(){$('#modalHost').innerHTML='';}
function archiveCurrentRace(){if(!state.race)return;const idx=state.archive.findIndex(r=>r.id===state.race.id);if(idx>=0)state.archive[idx]=JSON.parse(JSON.stringify(state.race));else state.archive.push(JSON.parse(JSON.stringify(state.race)));save(KEYS.archive,state.archive);toast('Соревнование сохранено в архив');}

lapwiz.addEventListener('pass',e=>processPass(e.detail.transponder,e.detail.deviceMs,'LAPWIZ'));lapwiz.addEventListener('status',()=>updateHeader());
window.addEventListener('pointerdown',()=>lapwiz.ensureAudio(),{once:true});
window.addEventListener('beforeunload',()=>persistAll());

$('#designQuickBtn')?.addEventListener('click',openDesignLab);
applySettings();render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
