'use strict';

export const SCORE_TABLE = [50,45,42,40,39,38,37,36,35,34,33,32,31,30,29,28];
export const EVENT_POINTS = [25,18,15,12,10,8,6,4,2,1];
export const FINAL_A_RUNS = ['A1','A2','A3'];

export function uid(prefix='id'){return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
export function deepClone(v){return JSON.parse(JSON.stringify(v));}

export function makeRace(input={}){
  const now=new Date().toISOString();
  return {
    id:uid('race'),eventName:input.eventName||'Новая гонка',clubName:input.clubName||'Legion RC',eventDate:input.eventDate||new Date().toISOString().slice(0,10),eventLocation:input.eventLocation||'',eventStatus:input.eventStatus||'club',championshipId:input.championshipId||'',championshipStageNumber:input.championshipStageNumber||null,qualifyingCount:Number(input.qualifyingCount||4),publishAllowed:false,
    pilots:[],heats:[],finals:[],finalProtocol:[],exactTieLots:{},stage:'setup',lifecycleStatus:'active',createdAt:now,updatedAt:now,completedAt:'',
    raceSettings:{qualificationMinutes:Number(input.qualificationMinutes||5),finalLaps:Number(input.finalLaps||7),countdownSec:Number(input.countdownSec||5),minLapSec:Number(input.minLapSec||2)},
    runtime:{activeEventKey:'',session:null,eventResults:{},eventLog:[]}
  };
}

export function makePilot(profile={},registrationOrder=1){
  return {id:profile.id||uid('pilot'),profileId:profile.profileId||profile.id||'',name:profile.name||'Пилот',club:profile.club||'',city:profile.city||'',photo:profile.photo||'',transponder:String(profile.transponder||''),registrationOrder,qualifying:[],best3:0,points:0,best3Rounds:[],finalResults:[]};
}
export function getPilot(race,id){return race.pilots.find(p=>String(p.id)===String(id));}

export function getPoints(place){if(!Number.isInteger(place)||place<1)return 0;return SCORE_TABLE[place-1]??Math.max(1,29-place);}
export function qualifyingResultRank(result){if(!result)return 10000;if(result.status==='FIN')return result.place;if(result.status==='DNF')return 100+(result.dnfOrder||99);if(result.status==='DNS')return 300;if(result.status==='DSQ')return 400;return 500;}
export function savePilotResult(pilot,round,heat,resultValue,dnfOrder=null){
  const existing=pilot.qualifying.find(r=>r.round===round);const isPlace=Number.isInteger(resultValue);const record={round,heat,place:isPlace?resultValue:null,status:isPlace?'FIN':resultValue,dnfOrder:resultValue==='DNF'&&Number.isInteger(dnfOrder)?dnfOrder:null,points:isPlace?getPoints(resultValue):0};
  if(existing)Object.assign(existing,record);else pilot.qualifying.push(record);
}
export function getBest3Results(pilot){return [...pilot.qualifying].sort((a,b)=>{if(b.points!==a.points)return b.points-a.points;const rd=qualifyingResultRank(a)-qualifyingResultRank(b);if(rd!==0)return rd;return b.round-a.round;}).slice(0,3);}
export function getDiscardedResults(pilot){const sel=new Set(getBest3Results(pilot).map(i=>`${i.round}:${i.heat}`));return pilot.qualifying.filter(i=>!sel.has(`${i.round}:${i.heat}`)).sort((a,b)=>{if(b.points!==a.points)return b.points-a.points;const rd=qualifyingResultRank(a)-qualifyingResultRank(b);if(rd!==0)return rd;return b.round-a.round;});}
export function calculateBest3(pilot){const best=getBest3Results(pilot);pilot.best3=best.reduce((s,r)=>s+r.points,0);pilot.points=pilot.best3;pilot.best3Rounds=best.map(r=>r.round);}
function placeHistogram(results,maxPlace=16){const h=[];for(let p=1;p<=maxPlace;p++)h.push(results.filter(r=>r.status==='FIN'&&r.place===p).length);return h;}
function compareNumberArraysDesc(a,b){const len=Math.max(a.length,b.length);for(let i=0;i<len;i++){const av=a[i]??-Infinity,bv=b[i]??-Infinity;if(bv!==av)return bv-av;}return 0;}
function compareResultArraysByQuality(a,b){const len=Math.max(a.length,b.length);for(let i=0;i<len;i++){const ar=a[i],br=b[i];if(!ar&&!br)continue;if(!ar)return 1;if(!br)return -1;if(br.points!==ar.points)return br.points-ar.points;const rd=qualifyingResultRank(ar)-qualifyingResultRank(br);if(rd!==0)return rd;}return 0;}
export function comparePilotsWithoutLot(race,a,b){if(b.best3!==a.best3)return b.best3-a.best3;const bestA=getBest3Results(a),bestB=getBest3Results(b);const hd=compareNumberArraysDesc(placeHistogram(bestA),placeHistogram(bestB));if(hd!==0)return hd;const dd=compareResultArraysByQuality(getDiscardedResults(a),getDiscardedResults(b));if(dd!==0)return dd;for(let round=race.qualifyingCount;round>=1;round--){const rd=qualifyingResultRank(a.qualifying.find(r=>r.round===round))-qualifyingResultRank(b.qualifying.find(r=>r.round===round));if(rd!==0)return rd;}return 0;}
export function comparePilots(race,a,b){const s=comparePilotsWithoutLot(race,a,b);if(s!==0)return s;const la=race.exactTieLots?.[String(a.id)],lb=race.exactTieLots?.[String(b.id)];if(Number.isInteger(la)&&Number.isInteger(lb)&&la!==lb)return la-lb;return (a.registrationOrder||9999)-(b.registrationOrder||9999);}
export function updateStandings(race){race.pilots.forEach(calculateBest3);race.pilots.sort((a,b)=>comparePilots(race,a,b));return race.pilots;}
export function getExactTieGroups(race){updateStandings(race);const groups=[];for(let i=0;i<race.pilots.length;){let g=[race.pilots[i]],j=i+1;while(j<race.pilots.length&&comparePilotsWithoutLot(race,race.pilots[i],race.pilots[j])===0){g.push(race.pilots[j]);j++;}if(g.length>1)groups.push(g);i=j;}return groups;}
export function runTieDraw(race){race.exactTieLots=race.exactTieLots||{};getExactTieGroups(race).forEach(group=>{const arr=[...group];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}arr.forEach((p,i)=>race.exactTieLots[String(p.id)]=i+1);});updateStandings(race);}

export function getHeatCount(pilotCount){if(pilotCount<=6)return 1;return Math.ceil(pilotCount/6);}
export function buildSnakeHeats(pilots,heatCount,round){const shift=pilots.length?(round-1)%pilots.length:0;const ordered=[...pilots.slice(shift),...pilots.slice(0,shift)];const heats=Array.from({length:heatCount},()=>[]);ordered.forEach((pilot,index)=>{const row=Math.floor(index/heatCount),column=index%heatCount,heatIndex=row%2===0?column:heatCount-1-column;heats[heatIndex].push(pilot);});return heats.filter(h=>h.length);}
export function createQualifyingData(race){race.heats=[];const pilots=[...race.pilots].sort((a,b)=>(a.registrationOrder||0)-(b.registrationOrder||0));const heatCount=getHeatCount(pilots.length);for(let round=1;round<=race.qualifyingCount;round++){buildSnakeHeats(pilots,heatCount,round).forEach((hp,idx)=>race.heats.push({key:`Q${round}-H${idx+1}`,type:'qualifying',label:`Квалификация ${round} · Заезд ${idx+1}`,round,heat:idx+1,pilots:hp.map(p=>p.id),saved:false,result:[],enabled:round===1&&idx===0,order:round*100+idx}));}}
export function prepareRace(race){race.finals=[];race.finalProtocol=[];race.exactTieLots={};race.stage='qualifying';race.pilots.forEach(p=>{p.qualifying=[];p.best3=0;p.points=0;p.finalResults=[];});createQualifyingData(race);normalizeQualifyingEnabled(race);return race;}
function normalizeQualifyingEnabled(race){const unsaved=race.heats.filter(h=>!h.saved).sort((a,b)=>a.order-b.order);race.heats.forEach(h=>h.enabled=false);if(unsaved[0])unsaved[0].enabled=true;}
export function saveQualifyingEvent(race,eventKey,result){const heat=race.heats.find(h=>h.key===eventKey);if(!heat||heat.saved)throw new Error('Заезд не найден или уже сохранён');heat.result=normalizeResult(result);heat.saved=true;heat.result.forEach((item,index)=>{const p=getPilot(race,item.pilotId);if(!p)return;if(item.status==='FIN')savePilotResult(p,heat.round,heat.heat,item.place??index+1);else savePilotResult(p,heat.round,heat.heat,item.status,item.dnfOrder);});updateStandings(race);normalizeQualifyingEnabled(race);if(race.heats.every(h=>h.saved)){const ties=getExactTieGroups(race).filter(g=>g.some(p=>!Number.isInteger(race.exactTieLots?.[String(p.id)])));if(ties.length)race.stage='tie';else generateFinals(race);}return heat;}
export function resolveQualificationTie(race){runTieDraw(race);generateFinals(race);return race.finals;}

function createFinal(name,pilots=[],options={}){return {key:`F-${name}`,name,label:options.label||name,type:options.type||'lcq',round:Number(options.round||0),order:Number(options.order||0),pilots:pilots.map(p=>p?.id||p),basePilots:pilots.map(p=>p?.id||p),result:[],saved:false,enabled:Boolean(options.enabled),advanceCount:Number(options.advanceCount||0)};}
export function finalByName(race,name){return race.finals.find(f=>f.name===name);}
function qualificationRankMap(race){const m=new Map();race.pilots.forEach((p,i)=>m.set(String(p.id),i+1));return m;}
function splitSnake(pilots,groupCount){const groups=Array.from({length:groupCount},()=>[]);if(groupCount<=1)return[pilots.slice()];let index=0,direction=1;pilots.forEach(p=>{groups[index].push(p);if(direction>0){if(index===groupCount-1){direction=-1;index-=1;}else index+=1;}else{if(index===0){direction=1;index+=1;}else index-=1;}});return groups;}
function addFinalARuns(race,pilots,enabledFirst=false,startOrder=1000){FINAL_A_RUNS.forEach((name,index)=>race.finals.push(createFinal(name,pilots,{type:'main',label:`Финал ${name}`,order:startOrder+index,enabled:enabledFirst&&index===0})));}
function createPreliminaryRound(race,pilotIdsOrObjects,round,startOrder){const groupCount=Math.ceil(pilotIdsOrObjects.length/6),groups=splitSnake(pilotIdsOrObjects,groupCount);groups.forEach((group,index)=>race.finals.push(createFinal(`P${round}-${index+1}`,group,{type:'prelim',label:`Предварительный LCQ ${round}.${index+1}`,round,order:startOrder+index,enabled:true,advanceCount:1})));}
export function generateFinals(race){updateStandings(race);race.finals=[];race.finalProtocol=[];race.pilots.forEach(p=>p.finalResults=[]);const pilots=[...race.pilots],count=pilots.length;if(count<=6)addFinalARuns(race,pilots,true);else{const remaining=pilots.slice(4);if(count<=10)race.finals.push(createFinal('LCQ',remaining,{type:'single-lcq',label:'Заезд последнего шанса (LCQ)',order:100,enabled:true,advanceCount:2}));else if(count<=16){const groups=splitSnake(remaining,2);race.finals.push(createFinal('LCQ-B',groups[0],{type:'dual-lcq',label:'LCQ B',round:1,order:100,enabled:true,advanceCount:1}));race.finals.push(createFinal('LCQ-C',groups[1],{type:'dual-lcq',label:'LCQ C',round:1,order:101,enabled:true,advanceCount:1}));}else createPreliminaryRound(race,remaining,1,100);addFinalARuns(race,[],false);}race.stage='finals';return race.finals;}
function compareFinalResultItems(a,b){const r={FIN:0,DNF:1,DNS:2,DSQ:3};if(r[a.status]!==r[b.status])return r[a.status]-r[b.status];if(a.status==='FIN')return(a.place||999)-(b.place||999);if(a.status==='DNF')return(a.dnfOrder||999)-(b.dnfOrder||999);return 0;}
function classifiedForAdvancement(result){return result.filter(i=>i.status==='FIN'||i.status==='DNF');}
function setMainGrid(race,lastTwo){const qTop4=race.pilots.slice(0,4).map(p=>p.id),grid=[...qTop4,...lastTwo].slice(0,6);FINAL_A_RUNS.forEach((name,index)=>{const f=finalByName(race,name);if(f){f.pilots=[...grid];f.basePilots=[...grid];f.enabled=index===0;}});}
function processPreliminaryRound(race,round){const finals=race.finals.filter(f=>f.type==='prelim'&&f.round===round);if(!finals.length||!finals.every(f=>f.saved))return;const winners=finals.map(f=>classifiedForAdvancement(f.result)[0]?.pilotId).filter(Boolean);if(winners.length<=6){if(!finalByName(race,`LCQ-F${round}`))race.finals.push(createFinal(`LCQ-F${round}`,winners,{type:'final-lcq',label:'Заключительный LCQ',round:round+1,order:500+round,enabled:true,advanceCount:2}));}else{const next=round+1;if(!race.finals.some(f=>f.type==='prelim'&&f.round===next))createPreliminaryRound(race,winners,next,100+next*50);}}
function advanceFinalists(race,final){if(final.type==='single-lcq'){setMainGrid(race,classifiedForAdvancement(final.result).slice(0,2).map(i=>i.pilotId));return;}if(final.type==='dual-lcq'){const pair=race.finals.filter(f=>f.type==='dual-lcq');if(pair.every(f=>f.saved)){const rank=qualificationRankMap(race),w=pair.map(f=>classifiedForAdvancement(f.result)[0]?.pilotId).filter(Boolean).sort((a,b)=>(rank.get(String(a))||9999)-(rank.get(String(b))||9999));setMainGrid(race,w);}return;}if(final.type==='prelim'){processPreliminaryRound(race,final.round);return;}if(final.type==='final-lcq'){setMainGrid(race,classifiedForAdvancement(final.result).slice(0,2).map(i=>i.pilotId));return;}if(final.type==='main'){const idx=FINAL_A_RUNS.indexOf(final.name);if(idx<2){const n=finalByName(race,FINAL_A_RUNS[idx+1]);if(n)n.enabled=true;}else buildFinalProtocol(race);}}
export function saveFinalEvent(race,eventKey,result){const final=race.finals.find(f=>f.key===eventKey);if(!final||!final.enabled||final.saved)throw new Error('Финал закрыт или уже сохранён');final.result=normalizeResult(result).sort(compareFinalResultItems);final.saved=true;final.result.forEach((item,index)=>{const p=getPilot(race,item.pilotId);if(p)p.finalResults.push({final:final.name,place:item.place,status:item.status,dnfOrder:item.dnfOrder,order:index+1});});advanceFinalists(race,final);return final;}
function mainRunScore(item){return item?.status==='FIN'?Number(item.place||7):7;}
export function buildMainStandings(race){const rank=qualificationRankMap(race),main=FINAL_A_RUNS.map(n=>finalByName(race,n)).filter(Boolean),pilotIds=main[0]?.pilots||[];return pilotIds.map(pilotId=>{const results=main.map(f=>f.saved?(f.result.find(i=>String(i.pilotId)===String(pilotId))||{status:'DNS'}):null),scores=results.map(i=>i?mainRunScore(i):null),done=scores.filter(Number.isFinite),bestTwo=[...done].sort((a,b)=>a-b).slice(0,2),latest=[...scores].reverse().find(Number.isFinite);return{pilotId,results,scores,bestTwo,total:bestTwo.length?bestTwo.reduce((s,v)=>s+v,0):null,wins:results.filter(i=>i?.status==='FIN'&&i.place===1).length,seconds:results.filter(i=>i?.status==='FIN'&&i.place===2).length,lastScore:latest??9999,qRank:rank.get(String(pilotId))||9999};}).sort((a,b)=>{if(a.total===null&&b.total!==null)return 1;if(a.total!==null&&b.total===null)return-1;if(a.total!==b.total)return(a.total??9999)-(b.total??9999);return b.wins-a.wins||b.seconds-a.seconds||a.lastScore-b.lastScore||a.qRank-b.qRank;});}
export function buildFinalProtocol(race){const main=buildMainStandings(race),added=new Set(main.map(i=>String(i.pilotId))),eliminated=[],rank=qualificationRankMap(race),groups=new Map();race.finals.filter(f=>f.saved&&f.type!=='main').forEach(f=>{const k=f.type==='dual-lcq'?'dual-lcq':f.type==='prelim'?`prelim-${f.round}`:`${f.type}-${f.order}`;if(!groups.has(k))groups.set(k,{order:f.order,finals:[]});groups.get(k).order=Math.max(groups.get(k).order,f.order);groups.get(k).finals.push(f);});[...groups.values()].sort((a,b)=>b.order-a.order).forEach(g=>{const c=[];g.finals.forEach(f=>[...f.result].sort(compareFinalResultItems).forEach((i,index)=>c.push({...i,resultOrder:index+1,source:f.label})));c.sort((a,b)=>a.resultOrder-b.resultOrder||(rank.get(String(a.pilotId))||9999)-(rank.get(String(b.pilotId))||9999));c.forEach(i=>{if(!added.has(String(i.pilotId))){eliminated.push({pilotId:i.pilotId,status:i.status,source:i.source});added.add(String(i.pilotId));}});});race.pilots.forEach(p=>{if(!added.has(String(p.id)))eliminated.push({pilotId:p.id,status:'NC',source:'Квалификация'});});const rows=[...main.map(i=>({pilotId:i.pilotId,status:'FIN',source:`Финал A · ${i.total} очк.`})),...eliminated];race.finalProtocol=rows.map((i,index)=>({place:index+1,pilotId:i.pilotId,status:i.status,source:i.source,eventPoints:['DNS','DSQ'].includes(i.status)?0:(EVENT_POINTS[index]||0)}));race.stage='finished';race.lifecycleStatus='completed';race.completedAt=new Date().toISOString();return race.finalProtocol;}

export function normalizeResult(items){
  const arr=(items||[]).map(i=>({pilotId:i.pilotId,status:i.status||'FIN',place:i.status==='FIN'||!i.status?Number(i.place)||null:null,dnfOrder:i.status==='DNF'?Number(i.dnfOrder)||null:null}));
  const fins=arr.filter(i=>i.status==='FIN').sort((a,b)=>(a.place||999)-(b.place||999));fins.forEach((i,idx)=>i.place=idx+1);
  const dnfs=arr.filter(i=>i.status==='DNF');dnfs.forEach((i,idx)=>i.dnfOrder=i.dnfOrder||idx+1);
  return arr.sort(compareFinalResultItems);
}

export function eventList(race){
  const q=race.heats.map(h=>({...h,phase:'qualifying'}));const f=race.finals.map(x=>({...x,phase:'finals'}));return [...q,...f].sort((a,b)=>{if(a.phase!==b.phase)return a.phase==='qualifying'?-1:1;return(a.order||0)-(b.order||0);});
}
export function currentEvent(race){const all=eventList(race);return all.find(e=>!e.saved&&e.enabled)||all.find(e=>!e.saved&&e.phase==='qualifying')||null;}
export function eventStatus(race,event){if(event.saved)return'completed';const cur=currentEvent(race);if(cur&&cur.key===event.key)return'current';if(event.enabled)return'ready';return'locked';}
export function eventRule(race,event){if(!event)return null;if(event.type==='qualifying')return{mode:'qualification',limitType:'time',durationMin:race.raceSettings.qualificationMinutes,targetLaps:0,minLapSec:race.raceSettings.minLapSec,finishCurrentLap:true};return{mode:'race',limitType:'laps',durationMin:0,targetLaps:race.raceSettings.finalLaps,minLapSec:race.raceSettings.minLapSec,finishCurrentLap:true};}
export function getEventPilots(race,event){return(event?.pilots||[]).map(id=>getPilot(race,id)).filter(Boolean);}
