'use strict';

const UUID={SERVICE:'0000fff0-0000-1000-8000-00805f9b34fb',COMMAND:'0000fff3-0000-1000-8000-00805f9b34fb',NOTIFY:'0000fff4-0000-1000-8000-00805f9b34fb'};
const STOP='0F03040005FFFF';
const hexToBytes=hex=>Uint8Array.from((hex.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));
const bytesToHex=bytes=>Array.from(bytes).map(b=>b.toString(16).padStart(2,'0').toUpperCase()).join('');
function buildProtocolPacket(command,payload=[]){const out=[0x0F,payload.length+3,command,0,...payload];const checksum=(command+payload.reduce((a,b)=>a+b,0)+1)&0xFF;out.push(checksum,0xFF,0xFF);return Uint8Array.from(out);}
function buildStartWork(settings){const type=settings.mode==='practice'?3:settings.mode==='qualification'?1:2,rule=settings.limitType==='laps'?1:0;let total;if(type===3)total=57600;else if(rule===1)total=Math.max(1,Math.min(65535,Math.round(settings.targetLaps)));else total=Math.max(1,Math.min(65535,Math.round(settings.durationMin*60)));const u16=n=>[(n>>8)&255,n&255];const minLap=Math.max(1,Math.min(65535,Math.round(Number(settings.minLapSec)||1)));return buildProtocolPacket(0x03,[type,rule,...u16(total),...u16(60),...u16(5),...u16(minLap)]);}

export class LapWizCore extends EventTarget{
  constructor(){super();this.device=null;this.server=null;this.cmdChar=null;this.notifyChar=null;this.connected=false;this.running=false;this.rxBuffer=[];this.pending={start:null,stop:null};this.sound=true;this.audioCtx=null;}
  emit(type,detail={}){this.dispatchEvent(new CustomEvent(type,{detail}));}
  async connect(){if(!navigator.bluetooth)throw new Error('Web Bluetooth недоступен. Нужен Chrome/Android и HTTPS.');const device=await navigator.bluetooth.requestDevice({filters:[{namePrefix:'LapWiz'}],optionalServices:[UUID.SERVICE]});device.addEventListener('gattserverdisconnected',()=>this.onDisconnected());const server=await device.gatt.connect(),service=await server.getPrimaryService(UUID.SERVICE),cmd=await service.getCharacteristic(UUID.COMMAND),notify=await service.getCharacteristic(UUID.NOTIFY);await notify.startNotifications();notify.addEventListener('characteristicvaluechanged',e=>this.onNotify(e));this.device=device;this.server=server;this.cmdChar=cmd;this.notifyChar=notify;this.connected=true;this.rxBuffer=[];this.emit('status',{connected:true,name:device.name||'LapWiz'});return device.name||'LapWiz';}
  async disconnect(){try{if(this.running)await this.stop();}catch{}if(this.device?.gatt?.connected)this.device.gatt.disconnect();this.onDisconnected();}
  onDisconnected(){const was=this.connected;this.connected=false;this.running=false;this.cmdChar=null;this.notifyChar=null;this.server=null;if(was)this.emit('status',{connected:false,error:'Bluetooth-соединение разорвано'});}
  ack(type,timeout=1800){if(this.pending[type])this.pending[type].reject(new Error('Предыдущая команда отменена'));let timer;return new Promise((resolve,reject)=>{timer=setTimeout(()=>{this.pending[type]=null;reject(new Error(`Нет подтверждения ${type.toUpperCase()}`));},timeout);this.pending[type]={resolve:v=>{clearTimeout(timer);this.pending[type]=null;resolve(v);},reject:e=>{clearTimeout(timer);this.pending[type]=null;reject(e);}};});}
  async write(packet,label='HEX'){if(!this.cmdChar)throw new Error('LapWiz не подключён');const bytes=typeof packet==='string'?hexToBytes(packet):packet;if(this.cmdChar.writeValueWithoutResponse)await this.cmdChar.writeValueWithoutResponse(bytes);else await this.cmdChar.writeValue(bytes);this.emit('log',{kind:'tx',label,raw:bytesToHex(bytes)});}
  async start(settings){const ack=this.ack('start');await this.write(buildStartWork(settings),'START');await ack;this.running=true;this.emit('status',{connected:true,running:true,name:this.device?.name||'LapWiz'});}
  async stop(){if(!this.connected||!this.cmdChar){this.running=false;return;}const ack=this.ack('stop');await this.write(STOP,'STOP');try{await ack;}finally{this.running=false;this.emit('status',{connected:true,running:false,name:this.device?.name||'LapWiz'});}}
  onNotify(event){const view=event.target.value,bytes=new Uint8Array(view.buffer,view.byteOffset,view.byteLength);this.rxBuffer.push(...bytes);this.extractFrames();}
  extractFrames(){while(this.rxBuffer.length){const start=this.rxBuffer.indexOf(0x0F);if(start<0){this.rxBuffer=[];return;}if(start>0)this.rxBuffer.splice(0,start);if(this.rxBuffer.length<2)return;const total=this.rxBuffer[1]+4;if(total<7||total>260){this.rxBuffer.shift();continue;}if(this.rxBuffer.length<total)return;this.handleFrame(new Uint8Array(this.rxBuffer.splice(0,total)));}}
  handleFrame(frame){const cmd=frame[2],raw=bytesToHex(frame);if(cmd===0x03&&frame[1]===0x04){const result=frame[4]??0;if(this.pending.start){result===0?this.pending.start.resolve(frame):this.pending.start.reject(new Error(`START result=${result}`));}return;}if(cmd===0x04&&frame[1]===0x04){const result=frame[4]??0;if(this.pending.stop){result===0?this.pending.stop.resolve(frame):this.pending.stop.reject(new Error(`STOP result=${result}`));}return;}if(cmd===0x02&&frame.length>=13){const id=((frame[4]<<8)|frame[5])>>>0,ticks=((((frame[6]<<24)>>>0)+(frame[7]<<16)+(frame[8]<<8)+frame[9])>>>0);this.emit('pass',{transponder:String(id),deviceTicks:ticks,deviceMs:ticks*10,raw,source:'LAPWIZ'});return;}this.emit('log',{kind:'rx',raw});}
  ensureAudio(){try{this.audioCtx??=new (window.AudioContext||window.webkitAudioContext)();if(this.audioCtx.state==='suspended')this.audioCtx.resume();return this.audioCtx;}catch{return null;}}
  beep(ok=true){if(!this.sound)return;const ctx=this.ensureAudio();if(!ctx)return;const tone=(freq,dur,vol,delay=0)=>{const t=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+dur+.02);};if(ok)tone(1250,.065,.18);else{tone(430,.09,.15);tone(330,.11,.13,.11);}}
  unknownBeep(){this.beep(false);}
}
