'use strict';
function bindView(){
 $$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
 $$('[data-action]').forEach(b=>b.addEventListener('click',()=>handleAction(b.dataset.action,b)));
 $$('[data-remove-race-pilot]').forEach(b=>b.addEventListener('click',()=>{if(state.race.stage!=='setup')return;state.race.pilots=state.race.pilots.filter(p=>p.id!==b.dataset.removeRacePilot);state.race.pilots.forEach((p,i)=>p.registrationOrder=i+1);persistRace();render();}));
 $$('[data-edit-pilot]').forEach(b=>b.addEventListener('click',()=>pilotModal(state.pilotDb.find(p=>p.id===b.dataset.editPilot),false,b.closest('.pilotTile')?.getBoundingClientRect?.()||null)));
  $$('[data-show-event]').forEach(b=>b.addEventListener('click',()=>raceResultsModal(b.dataset.showEvent)));
 $$('[data-widget-toggle]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.widgetToggle;state.widgetCollapsed[k]=!state.widgetCollapsed[k];render();}));
 $$('[data-toggle-widget]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.toggleWidget;state.widgetCollapsed[id]=!state.widgetCollapsed[id];render();}));
 $$('[data-open-champ]').forEach(b=>b.addEventListener('click',()=>{state.activeChampionshipId=b.dataset.openChamp;state.champTab='stages';nav('championshipDetail');}));
 $$('[data-champ-tab]').forEach(b=>b.addEventListener('click',()=>{state.champTab=b.dataset.champTab;render();}));
 $$('[data-champ-remove-pilot]').forEach(b=>b.addEventListener('click',()=>{const c=activeChampionship();if(!c)return;c.pilotIds=c.pilotIds.filter(id=>id!==b.dataset.champRemovePilot);save(KEYS.champ,state.championships);render();}));
 $$('[data-edit-stage]').forEach(b=>b.addEventListener('click',()=>champStageModal(b.dataset.editStage)));
 $$('[data-start-stage]').forEach(b=>b.addEventListener('click',()=>startChampStage(b.dataset.startStage)));
 $$('[data-continue-stage]').forEach(b=>b.addEventListener('click',()=>continueChampStage(b.dataset.continueStage)));
 $$('[data-stage-results]').forEach(b=>b.addEventListener('click',()=>showRaceResultsById(b.dataset.stageResults)));
 $$('[data-restore-archive]').forEach(b=>b.addEventListener('click',()=>restoreRaceFromArchive(b.dataset.restoreArchive)));
 $$('[data-delete-archive]').forEach(b=>b.addEventListener('click',()=>deleteArchivedRace(b.dataset.deleteArchive)));
 const qSel=$('#qLimitType'),fSel=$('#finalLimitType');if(qSel)qSel.addEventListener('change',syncRaceRuleFields);if(fSel)fSel.addEventListener('change',syncRaceRuleFields);syncRaceRuleFields();
 const darkToggle=$('#darkToggle');if(darkToggle)darkToggle.addEventListener('change',()=>{state.settings.theme=darkToggle.checked?'dark':'light';save(KEYS.settings,state.settings);applySettings();const c=$('#appBgColor');if(c&&!state.settings.backgroundColor)c.value=appBackgroundFallbackColor();});
 const bgColor=$('#appBgColor');if(bgColor)bgColor.addEventListener('input',()=>{state.settings.backgroundColor=bgColor.value;try{save(KEYS.settings,state.settings);}catch(e){toast('Не удалось сохранить цвет фона');return;}applyAppBackground();});
 const bgFile=$('#appBgFile'),bgUpload=$('#appBgUpload'),bgClear=$('#appBgClear'),bgState=$('#appBgState');if(bgUpload&&bgFile)bgUpload.addEventListener('click',()=>bgFile.click());
 if(bgFile)bgFile.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(bgState)bgState.textContent='ОБРАБОТКА…';const data=await resizeAppBackground(file),prev=state.settings.backgroundImage||'';state.settings.backgroundImage=data;try{save(KEYS.settings,state.settings);}catch(err){state.settings.backgroundImage=prev;throw new Error('Недостаточно локальной памяти для фона');}applyAppBackground();if(bgState)bgState.textContent='ФОН ЗАГРУЖЕН';if(bgClear)bgClear.disabled=false;toast('Фон обновлён');}catch(err){if(bgState)bgState.textContent=state.settings.backgroundImage?'ФОН ЗАГРУЖЕН':'БЕЗ ФОТО';toast(err.message);}finally{e.target.value='';}});
 if(bgClear)bgClear.addEventListener('click',()=>{state.settings.backgroundImage='';try{save(KEYS.settings,state.settings);}catch{}applyAppBackground();bgClear.disabled=true;if(bgState)bgState.textContent='БЕЗ ФОТО';});
 bindManualPasses();
}

function bindManualPasses(){$$('[data-manual-pass]').forEach(b=>b.onclick=()=>{const p=getPilot(state.race,b.dataset.manualPass);if(p)processPilotPass(p,null,'MANUAL');});}

async function legacyHandleAction(action){
 if(action==='home')return nav('home');if(action==='open-rx'||action==='open-current')return nav(state.race?.stage&&state.race.stage!=='setup'?'cockpit':'rallySetup');if(action==='cockpit')return nav('cockpit');
 if(action==='create-race'){const input={eventName:$('#raceName').value.trim()||'Legion RX Cup',eventDate:$('#raceDate').value,eventLocation:$('#raceLocation').value.trim(),championshipId:$('#raceChamp').value,qualificationLimitType:state.settings.qualificationLimitType,qualificationMinutes:state.settings.qualificationMinutes,qualificationLaps:state.settings.qualificationLaps,finalLimitType:state.settings.finalLimitType,finalMinutes:state.settings.finalMinutes,finalLaps:state.settings.finalLaps,minLapSec:state.settings.minLapSec,countdownSec:state.settings.countdownSec,warmupMinutes:state.settings.warmupMinutes};state.race=makeRace(input);if(input.championshipId){const c=state.championships.find(x=>x.id===input.championshipId);state.race.championshipStageNumber=(c?.stages?.reduce((m,s)=>Math.max(m,s.number||0),0)||0)+1;}persistRace();return render();}
 if(action==='quick-pilot')return pilotModal(null,true);if(action==='add-db-pilot')return pilotPicker();
 if(action==='prepare-race'){if(state.race.pilots.length<2)return toast('Нужно минимум два пилота');state.race.eventName=$('#raceName').value.trim()||state.race.eventName;state.race.eventDate=$('#raceDate').value;state.race.eventLocation=$('#raceLocation').value.trim();state.race.championshipId=$('#raceChamp').value;state.race.qualifyingCount=Number($('#qCount').value);state.race.raceSettings={qualificationLimitType:$('#qLimitType').value,qualificationMinutes:Number($('#qMinutes').value)||5,qualificationLaps:Number($('#qLaps').value)||8,finalLimitType:$('#finalLimitType').value,finalMinutes:Number($('#finalMinutes').value)||5,finalLaps:Number($('#finalLaps').value)||7,minLapSec:Number($('#minLap').value)||2,countdownSec:Math.max(1,Math.min(10,Number($('#raceCountdownSec')?.value)||state.settings.countdownSec||10)),warmupMinutes:Math.max(1,Math.min(5,Number($('#raceWarmupMinutes')?.value)||state.settings.warmupMinutes||2))};prepareRace(state.race);persistRace();state.session=null;return nav('cockpit');}
 if(action==='delete-race'){if(confirm('Удалить текущее соревнование?')){state.race=null;save(KEYS.race,null);nav('home');}return;}
 if(action==='toggle-events'){state.mobileEvents=true;return render();}if(action==='close-events'){state.mobileEvents=false;return render();}if(action==='toggle-widgets'){state.mobileWidgets=true;return render();}if(action==='close-widgets'){state.mobileWidgets=false;return render();}
 if(action==='race-results')return raceResultsModal();
 if(action==='tie-draw'){resolveQualificationTie(state.race);persistRace();state.session=null;toast('Жеребьёвка проведена. Финалы сформированы.');return render();}
 if(action==='toggle-results'){state.resultsOpen=!state.resultsOpen;state.widgetCollapsed.results=!state.resultsOpen;return render();}if(action==='start-session')return beginCountdown();if(action==='pause-session')return togglePause();if(action==='add-minute')return addMinute();if(action==='manual-pass-picker')return manualPassPicker();if(action==='next-event')return openCurrentEventResultEditor();if(action==='finish-session')return finishSession();if(action==='stop-session')return stopSession();if(action==='save-event-result')return openCurrentEventResultEditor();
 if(action==='lap-connect'){try{lapwiz.ensureAudio();await lapwiz.connect();toast('LapWiz подключён');updateHeader();render();}catch(e){toast(e.message);}return;}if(action==='lap-disconnect'){await lapwiz.disconnect();toast('LapWiz отключён');updateHeader();render();return;}
 if(action==='new-db-pilot')return pilotModal();if(action==='new-champ')return championshipModal();if(action==='new-champ-stage')return champStageModal();if(action==='champ-add-pilots')return champPilotPicker();if(action==='back-champs')return nav('championships');if(action==='save-champ-settings')return saveChampionshipSettings({name:$('#champNameEdit')?.value,season:$('#champSeasonEdit')?.value,stagesPlanned:$('#champStagesEdit')?.value});if(action==='open-design-lab')return openDesignLab();
 if(action==='audio-enable'){const ok=await ensureRaceAudioFromGesture({confirmation:true});if(ok)toast('Звук готов');updateOfflineReadyUi();return;}
 if(action==='offline-check'){const ok=await offlineReady.check();if(ok&&!announcer.localAudioReady)await announcer.hydrateOfflineAudio();updateOfflineReadyUi();updateAppUpdateUi();toast(ok?'OFFLINE READY ✓':'Локальный пакет неполный');return;}
 if(action==='update-check'){if(!navigator.onLine){toast('Нет сети — текущая версия работает Offline');updateAppUpdateUi();return;}if(!confirm('Проверить и скачать обновление? Используйте стабильное соединение. Текущая рабочая версия останется активной, пока новый пакет не будет скачан полностью.'))return;await appUpdater.check();updateAppUpdateUi();render();return;}
 if(action==='update-install'){if(!appUpdater.snapshot().ready)return toast('Готового обновления нет');if(!confirm('Новая версия полностью скачана и проверена. Установить её сейчас? Приложение перезапустится.'))return;await appUpdater.activate();return;}
 if(action==='test-good-race'){if(!await ensureRaceAudioFromGesture())return;announcer.play('goodRace',{wait:false,force:true});return;}
 if(action==='test-start-horn'){if(!await ensureRaceAudioFromGesture())return;announcer.play('startRace',{wait:false,force:true});return;}
 if(action==='test-bleep'){if(!await ensureRaceAudioFromGesture())return;announcer.playBleep({force:true});return;}
 if(action==='save-settings'){state.settings.theme=$('#darkToggle')?.checked?'dark':'light';state.settings.lang=$('#langSelect')?.value||'ru';state.settings.lapSound=Boolean($('#soundToggle')?.checked);state.settings.minLapSec=Number($('#settingsMinLap')?.value)||2;state.settings.qualificationLimitType=$('#settingsQLimit')?.value||'time';state.settings.qualificationMinutes=Number($('#settingsQMin')?.value)||5;state.settings.qualificationLaps=Number($('#settingsQLaps')?.value)||8;state.settings.finalLimitType=$('#settingsFLimit')?.value||'laps';state.settings.finalLaps=Number($('#settingsFLaps')?.value)||7;state.settings.finalMinutes=Number($('#settingsFMin')?.value)||5;state.settings.countdownSec=Math.max(1,Math.min(10,Number($('#settingsCountdown')?.value)||10));state.settings.warmupMinutes=Math.max(1,Math.min(5,Number($('#settingsWarmupMinutes')?.value)||2));state.settings.announcerEnabled=Boolean($('#announcerToggle')?.checked);state.settings.pilotVoiceEnabled=Boolean($('#pilotVoiceToggle')?.checked);state.settings.voiceStartCall=Boolean($('#voiceStartCallToggle')?.checked);state.settings.voiceBestLap=Boolean($('#voiceBestLapToggle')?.checked);state.settings.voiceFinish=Boolean($('#voiceFinishToggle')?.checked);state.settings.voiceResults=Boolean($('#voiceResultsToggle')?.checked);state.settings.voiceService=Boolean($('#voiceServiceToggle')?.checked);delete state.settings.pilotVoiceProxyUrl;state.settings.startVoiceMode='custom';announcer.enabled=state.settings.announcerEnabled;announcer.startMode='custom';if(state.race?.raceSettings&&state.race.stage==='setup'){state.race.raceSettings.countdownSec=state.settings.countdownSec;state.race.raceSettings.warmupMinutes=state.settings.warmupMinutes;persistRace();}save(KEYS.settings,state.settings);applySettings();toast('Настройки сохранены');return render();}
 if(action==='complete-competition')return competitionFinishConfirmModal();if(action==='archive-race'){completeCompetition();return;}
}

function bind415PilotStats(){if(state._pilotStatsDelegated)return;state._pilotStatsDelegated=true;document.addEventListener('click',e=>{const b=e.target.closest?.('[data-pilot-stats]');if(!b)return;pilotLapStatsModal(b.dataset.pilotStats,b.dataset.statsContext||'race',b.dataset.trackId||b.dataset.eventKey||'');});}
function bind415(){
  $$('[data-track-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.trackAction;if(a==='open')return nav(state.trackDay?.status==='active'?'trackDayCockpit':'trackDaySetup');if(a==='open-active')return nav('trackDayCockpit');if(a==='home')return nav('home');if(a==='setup'){if(state.trackDay?.status==='active')return toast('Сначала завершите текущую Track Day сессию');state.trackDay=newTrackDayDraft();persistTrackDays();return nav('trackDaySetup');}if(a==='select-all'){pilotSelectAllPracticeModels();return;}if(a==='start')return startTrackDayFromUI();if(a==='finish'){if(confirm('Завершить Track Day сейчас?'))return finishTrackDay('Сессия завершена судьёй');return;}if(a==='report')return trackDayReportModal(state.trackDay);if(a==='clear-active'){state.trackDay=null;persistTrackDays();return nav('trackDaySetup');}if(a==='lap-connect'){try{lapwiz.ensureAudio();await lapwiz.connect();if(state.trackDay?.status==='active'&&!lapwiz.running)await lapwiz.start({mode:'practice',limitType:'time',durationMin:960,targetLaps:0,minLapSec:trackMinLapSec(state.trackDay)});toast('LapWiz подключён');render();}catch(e){toast(e.message);}return;}});
  $$('[data-track-model-toggle]').forEach(b=>b.onclick=()=>pilotTogglePracticeModel(b.dataset.trackModelToggle,b.dataset.modelId,true));
  $$('[data-track-report]').forEach(b=>b.onclick=()=>trackDayReportModal((state.trackDays||[]).find(x=>x.id===b.dataset.trackReport)));
  $$('[data-track-delete]').forEach(b=>b.onclick=()=>{if(!confirm('Удалить этот Track Day отчёт?'))return;state.trackDays=state.trackDays.filter(x=>x.id!==b.dataset.trackDelete);persistTrackDays();render();});
  $$('[data-race-skip-current]').forEach(b=>b.onclick=()=>quickSkipCurrentRace());$$('[data-race-manage]').forEach(b=>b.onclick=()=>raceManageModal());bind415PilotStats();

}
