'use strict';
/* LEGION RX · CLASSIC RC EFRA runtime. Independent Classic RC runtime.
   Test acceleration is consumed only through raceTestSourceAdapter; sport rules stay untouched. */
const ClassicRCRuntime=(()=>{
  let ticker=null,countdownTimer=null;
  const blank=()=>({laps:0,lapTimes:[],bestLapMs:Infinity,lastLapMs:null,lastPassPerf:null,lastElapsedAtPass:null,lastDeviceMs:null,started:false,startElapsedMs:null,elapsedMs:0,timeMs:0,finished:false,finishedAt:null,status:'READY'});
  const formatLapMs=ms=>{const n=Number(ms);if(!Number.isFinite(n)||n<0)return'—';const sec=n/1000;return sec<60?sec.toFixed(3):`${Math.floor(sec/60)}:${(sec%60).toFixed(3).padStart(6,'0')}`;};
  function event(){return ClassicRCEngine.currentEvent();}
  function competition(){return ClassicRCEngine.get();}
  function session(){return competition()?.session||null;}
  function active(){return Boolean(competition()&&event());}
  function testSourceActive(){return !lapwiz.connected&&typeof raceTestSourceAdapter!=='undefined'&&raceTestSourceAdapter.available()&&raceTestSourceAdapter.isEnabled();}
  function testScale(){return testSourceActive()?Math.max(1,Number(raceTestSourceAdapter.scale())||1):1;}
  function ensureCompetitionClock(){
    const c=competition();if(!c)return null;const real=Date.now(),target=testScale();
    if(!c.runtimeClock)c.runtimeClock={realAnchor:real,virtualAnchor:real,scale:target};
    const st=c.runtimeClock,oldScale=Math.max(1,Number(st.scale)||1);
    if(oldScale!==target){const virtual=Number(st.virtualAnchor||real)+(real-Number(st.realAnchor||real))*oldScale;st.virtualAnchor=virtual;st.realAnchor=real;st.scale=target;ClassicRCEngine.persist();}
    return st;
  }
  function rawNowEpoch(){const st=ensureCompetitionClock();if(!st)return Date.now();return Number(st.virtualAnchor)+(Date.now()-Number(st.realAnchor))*Math.max(1,Number(st.scale)||1);}
  function nowEpoch(){const c=competition();if(c?.directorHold?.active)return Number(c.directorHold.atEpoch)||rawNowEpoch();return rawNowEpoch();}
  function syncSessionScale(s){
    if(!s||!s.startedAtPerf||s.phase==='paused')return;const target=testScale(),old=Math.max(1,Number(s.clockScale)||1);if(old===target)return;
    const current=(Number(s.elapsedBeforePause)||0)+(performance.now()-s.startedAtPerf)*old;s.elapsedBeforePause=current;s.startedAtPerf=performance.now();s.clockScale=target;ClassicRCEngine.persist();
  }
  function elapsed(s=session()){if(!s)return 0;if(Number.isFinite(s.elapsedFinalMs))return s.elapsedFinalMs;syncSessionScale(s);const base=Number(s.elapsedBeforePause)||0;if(s.phase==='paused'||!s.startedAtPerf)return base;return base+(performance.now()-s.startedAtPerf)*Math.max(1,Number(s.clockScale)||1);}
  function ensureSession(){const c=competition(),ev=event();if(!c||!ev)return null;if(!c.session||c.session.eventKey!==ev.key)c.session={eventKey:ev.key,phase:'ready',startedAtPerf:null,startedAtEpoch:null,elapsedBeforePause:0,elapsedFinalMs:null,countdownLeft:10,directorStartOverride:false,clockScale:testScale(),live:Object.fromEntries(ev.pilots.map(id=>[id,blank()])),lastPass:'',finishReason:'',timeExpired:false,oneMinuteAnnounced:false};return c.session;}
  function pilots(){const ev=event();return ev?ClassicRCEngine.pilots(ClassicRCEngine.startPilots(ev)):[];}
  function liveRanking(){const ps=pilots(),s=session();if(!s)return ps;const order=new Map(ps.map((p,i)=>[String(p.id),i]));return [...ps].sort((a,b)=>{const A=s.live[a.id]||blank(),B=s.live[b.id]||blank();if(B.laps!==A.laps)return B.laps-A.laps;if(A.finished!==B.finished)return A.finished?-1:1;const ta=A.timeMs||A.elapsedMs||Infinity,tb=B.timeMs||B.elapsedMs||Infinity;if(ta!==tb)return ta-tb;return(order.get(String(a.id))||0)-(order.get(String(b.id))||0);});}
  function startTicker(){stopTicker();ticker=setInterval(()=>{if(!active())return;checkLimit();if(typeof classicRCUpdateDynamic==='function')classicRCUpdateDynamic();},120);}
  function stopTicker(){if(ticker){clearInterval(ticker);ticker=null;}}
  function stopCountdown(){if(countdownTimer){clearTimeout(countdownTimer);countdownTimer=null;}}
  function durationMs(){const ev=event();return Math.max(1/60,Number(ev?.durationMin||ClassicRCEngine.category().raceMinutes))*60000;}
  function countdownStep(s){
    if(!session()||session()!==s||s.phase!=='countdown')return stopCountdown();
    countdownTimer=setTimeout(()=>{if(!session()||session()!==s||s.phase!=='countdown')return stopCountdown();s.countdownLeft--;try{ClassicRCAudio.countdownTick(s.countdownLeft);}catch{}ClassicRCEngine.persist();if(typeof classicRCUpdateDynamic==='function')classicRCUpdateDynamic();if(s.countdownLeft<=0){stopCountdown();const delay=Math.max(0,Number(s.startDelayMs)||0)/testScale();countdownTimer=setTimeout(()=>{countdownTimer=null;if(session()===s&&s.phase==='countdown')startNow();},delay);}else countdownStep(s);},Math.max(25,1000/testScale()));
  }
  async function beginStart(options={}){const c=competition(),ev=event(),s=ensureSession();if(!c||!ev||s.phase!=='ready'||c.directorHold?.active)return;
    const directorOverride=Boolean(options.directorOverride),delay=ev.stage==='final'?(1000+Math.floor(Math.random()*4001)):0,anticipated=nowEpoch()+10000+delay,check=ClassicRCEngine.canStartScheduleHeat(ev.key,anticipated,{ignoreMinGap:directorOverride});
    if(!check.ok&&check.earliestEpoch)return toast(`Рано: старт не раньше ${CompetitionScheduler.formatTime(check.earliestEpoch)}`);if(!check.ok)return toast(check.error||'Не удалось запустить заезд');
    s.phase='countdown';s.countdownLeft=10;s.startDelayMs=delay;s.directorStartOverride=directorOverride;s.clockScale=testScale();ClassicRCEngine.persist();render();stopCountdown();try{ClassicRCAudio.countdownTick(10);}catch{}countdownStep(s);
  }
  async function startNow(){const c=competition(),ev=event(),s=ensureSession();if(!c||!ev||s.phase!=='countdown')return;if(c.directorHold?.active){s.phase='ready';stopCountdown();ClassicRCEngine.persist();return render();}
    const now=nowEpoch(),directorOverride=Boolean(s.directorStartOverride),check=ClassicRCEngine.canStartScheduleHeat(ev.key,now,{ignoreMinGap:directorOverride});
    if(!check.ok&&check.earliestEpoch&&check.earliestEpoch>now){const virtualWait=Math.max(20,check.earliestEpoch-now+20),wait=Math.min(60000,virtualWait/testScale());s.lastPass=`ОЖИДАНИЕ СТАРТА · ${CompetitionScheduler.formatTime(check.earliestEpoch)}`;ClassicRCEngine.persist();return setTimeout(()=>{if(session()===s&&s.phase==='countdown')startNow();},wait);}
    if(!check.ok){s.phase='ready';ClassicRCEngine.persist();toast(check.error||'Не удалось запустить заезд');return render();}
    let lapwizStarted=false;try{if(lapwiz.connected&&!lapwiz.running){await lapwiz.start({mode:'race',limitType:'time',durationMin:Math.max(1/60,Number(ev.durationMin)||5),targetLaps:0,minLapSec:Number(c.settings.minLapSec)||2});lapwizStarted=true;}}catch(e){toast(`LapWiz START: ${e.message}`);s.phase='ready';ClassicRCEngine.persist();return render();}
    const sch=ClassicRCEngine.startScheduleHeat(ev.key,nowEpoch(),{directorOverride});if(!sch.ok){if(lapwizStarted&&lapwiz.running){try{await lapwiz.stop();}catch{}}s.phase='ready';ClassicRCEngine.persist();toast(sch.error||'Не удалось зафиксировать старт');return render();}
    s.phase='running';s.startedAtPerf=performance.now();s.startedAtEpoch=sch.item?.actualStartEpoch||nowEpoch();s.elapsedBeforePause=0;s.elapsedFinalMs=null;s.timeExpired=false;s.oneMinuteAnnounced=false;s.startDelayMs=0;s.directorStartOverride=false;s.clockScale=testScale();Object.keys(s.live).forEach(id=>s.live[id]=blank());s.lastPass=ev.stage==='qualifying'?'STAGGERED START · ожидаем стартовые пересечения':'СТАРТ';
    if(testSourceActive())raceTestSourceAdapter.startSession({pilots:pilots(),rule:{limitType:'time',durationMin:ev.durationMin,minLapSec:Number(c.settings.minLapSec)||2},getElapsed:()=>elapsed(session()),getLive:id=>session()?.live?.[id]});
    try{ClassicRCAudio.startSignal();}catch{}ClassicRCEngine.persist();startTicker();render();
  }
  async function pause(){const s=session();if(!s)return;if(s.phase==='paused')return resume();if(!['running','finishing'].includes(s.phase))return;s.elapsedBeforePause=elapsed(s);s.startedAtPerf=null;s.resumePhase=s.phase;s.phase='paused';if(testSourceActive())raceTestSourceAdapter.pause();if(lapwiz.connected&&lapwiz.running){try{await lapwiz.stop();}catch{}}ClassicRCEngine.persist();render();}
  async function resume(){const s=session(),ev=event();if(!s||s.phase!=='paused'||!ev||competition()?.directorHold?.active)return;try{if(lapwiz.connected&&!lapwiz.running)await lapwiz.start({mode:'race',limitType:'time',durationMin:Math.max(1/60,(durationMs()-s.elapsedBeforePause)/60000),targetLaps:0,minLapSec:Number(competition().settings.minLapSec)||2});}catch(e){return toast(`LapWiz RESUME: ${e.message}`);}s.phase=s.resumePhase||'running';s.startedAtPerf=performance.now();s.clockScale=testScale();Object.values(s.live).forEach(l=>{l.lastPassPerf=null;l.lastDeviceMs=null;});if(testSourceActive())raceTestSourceAdapter.resume();ClassicRCEngine.persist();startTicker();render();}
  async function finish(reason='Финиш судьёй'){const s=session();if(!s)return;stopCountdown();stopTicker();if(typeof raceTestSourceAdapter!=='undefined')raceTestSourceAdapter.stop();if(lapwiz.connected&&lapwiz.running){try{await lapwiz.stop();}catch{}}s.elapsedFinalMs=elapsed(s);s.phase='finished';s.finishReason=reason;Object.values(s.live).forEach(l=>{if(l.status==='DNS'||l.status==='DNF')return;if(l.started&&!l.finished){l.timeMs=l.timeMs||l.elapsedMs||s.elapsedFinalMs;l.finished=true;l.status='FIN';}else if(!l.started){l.finished=true;l.status='DNS';}});try{ClassicRCAudio.heatFinished({allPilots:/Все пилоты/i.test(String(reason)),stopped:String(reason)==='STOP'});}catch{}ClassicRCEngine.persist();render();}
  async function stop(){const s=session();if(!s)return;if(s.phase==='countdown'){stopCountdown();if(typeof raceTestSourceAdapter!=='undefined')raceTestSourceAdapter.stop();s.phase='ready';s.directorStartOverride=false;ClassicRCEngine.persist();return render();}return finish('STOP');}
  function checkLimit(){const ev=event(),s=session();if(!ev||!s||s.phase!=='running')return;const now=elapsed(s),limit=durationMs(),remaining=Math.max(0,limit-now);if(!s.oneMinuteAnnounced&&limit>60000&&remaining<=60000){s.oneMinuteAnnounced=true;try{ClassicRCAudio.service('oneMinuteLeft');}catch{}ClassicRCEngine.persist();}
    if(ev.stage==='qualifying'){
      const all=Object.values(s.live).every(l=>l.finished||(!l.started&&now>limit+60000));if(all&&now>limit)return finish('Квалификация завершена');
    }else if(['seeding','controlled','finalPractice'].includes(ev.stage)){
      if(now>=limit)return finish('Время практики истекло');
    }else if(ev.stage==='final'&&now>=limit&&!s.timeExpired){s.timeExpired=true;s.phase='finishing';s.lastPass='ВРЕМЯ ИСТЕКЛО · ФИНИШ ТЕКУЩЕГО КРУГА';try{ClassicRCAudio.timeExpired();}catch{}ClassicRCEngine.persist();}
  }
  function lapTime(l,elapsedNow,deviceMs,source,firstAsLap){if(firstAsLap&&!l.started)return elapsedNow;if(Number.isFinite(deviceMs)&&source==='LAPWIZ'&&Number.isFinite(l.lastDeviceMs)&&deviceMs>l.lastDeviceMs)return deviceMs-l.lastDeviceMs;if(Number.isFinite(l.lastElapsedAtPass))return Math.max(0,elapsedNow-l.lastElapsedAtPass);return null;}
  function processPass(detail={}){const c=competition(),ev=event(),s=session();if(!c||!ev||!s||!['running','finishing'].includes(s.phase))return false;const p=pilots().find(x=>String(x.transponder)===String(detail.transponder)||String(x.id)===String(detail.pilotId));if(!p)return false;const l=s.live[p.id]||blank(),now=performance.now(),e=elapsed(s),source=detail.source||'EXTERNAL',deviceMs=Number.isFinite(detail.deviceMs)?detail.deviceMs:null;
    const rollingStart=['seeding','controlled','finalPractice','qualifying'].includes(ev.stage);
    if(rollingStart&&!l.started){l.started=true;l.startElapsedMs=e;l.lastElapsedAtPass=e;l.lastPassPerf=now;l.lastDeviceMs=deviceMs;l.elapsedMs=0;l.timeMs=0;l.status='RACING';s.live[p.id]=l;s.lastPass=`${p.name} · START`;try{ClassicRCAudio.bleep();}catch{}ClassicRCEngine.persist();return true;}
    const firstAsLap=!rollingStart,lm=lapTime(l,e,deviceMs,source,firstAsLap),wasFinished=Boolean(l.finished),previousGlobalBest=Math.min(...Object.values(s.live).map(x=>Number(x.bestLapMs)).filter(x=>Number.isFinite(x)&&x>0),Infinity);if(!l.started){l.started=true;l.startElapsedMs=0;}let acceptedLap=false;if(Number.isFinite(lm)&&lm>=Math.max(250,Number(c.settings.minLapSec||2)*1000)){l.lapTimes.push(lm);l.laps=l.lapTimes.length;l.lastLapMs=lm;l.bestLapMs=Math.min(l.bestLapMs,lm);acceptedLap=true;}l.lastPassPerf=now;l.lastElapsedAtPass=e;l.lastDeviceMs=deviceMs;l.elapsedMs=e;l.timeMs=rollingStart?Math.max(0,e-Number(l.startElapsedMs||0)):e;l.status='RACING';
    if(ev.stage==='qualifying'&&l.started&&l.timeMs>=durationMs()){l.finished=true;l.finishedAt=e;l.status='FIN';}
    if(ev.stage==='final'&&s.phase==='finishing'){l.finished=true;l.finishedAt=e;l.status='FIN';}
    s.live[p.id]=l;s.lastPass=`${p.name} · ${l.laps} · ${Number.isFinite(lm)?formatLapMs(lm):'—'}`;if(acceptedLap){try{ClassicRCAudio.bleep();if(Number(lm)<previousGlobalBest)ClassicRCAudio.bestLap(p);}catch{}}if(!wasFinished&&l.finished){try{ClassicRCAudio.pilotFinished(p);}catch{}}ClassicRCEngine.persist();if(ev.stage==='final'&&Object.values(s.live).every(x=>x.finished||x.status==='DNS')&&s.phase==='finishing')finish('Все пилоты финишировали');return true;}
  function processPilotStatus(detail={}){const s=session();if(!s||!['running','finishing'].includes(s.phase))return false;const p=pilots().find(x=>String(x.transponder)===String(detail.transponder)||String(x.id)===String(detail.pilotId));if(!p)return false;const l=s.live[p.id]||blank(),status=String(detail.status||'').toUpperCase(),e=elapsed(s);if(status==='DNS'){l.status='DNS';l.finished=true;l.started=false;l.timeMs=0;l.elapsedMs=0;}else if(status==='DNF'){l.status='DNF';l.finished=true;l.finishedAt=e;l.timeMs=l.timeMs||l.elapsedMs||e;}else return false;s.live[p.id]=l;s.lastPass=`${p.name} · ${status}`;if(status==='DNF'){try{ClassicRCAudio.pilotFinished(p);}catch{}}ClassicRCEngine.persist();return true;}
  function handleSourceComplete(){const s=session();if(!s||!testSourceActive())return;if(['running','finishing'].includes(s.phase))finish('SIM завершил заезд');}
  function suggestedResult(){const ev=event(),s=session();if(!ev||!s)return[];const rank=liveRanking();let prevPerf=null,prevPlace=0;return rank.map((p,i)=>{const l=s.live[p.id]||blank(),status=l.status==='DNS'?'DNS':l.status==='DNF'?'DNF':l.started?'FIN':'DNS',perf={laps:Number(l.laps)||0,timeMs:Number(l.timeMs||l.elapsedMs)||0};let place=null;if(status!=='DNS'){place=prevPerf&&classicRCCompareLapsTime(perf,prevPerf)===0?prevPlace:i+1;prevPerf=perf;prevPlace=place;}return{pilotId:p.id,status,place,laps:perf.laps,timeMs:perf.timeMs,carNumber:(ev.pilots.indexOf(p.id)+1)};});}
  function saveResult(result){const ev=event(),s=session();if(!ev||!s||s.phase!=='finished')throw new Error('Сначала завершите заезд');ClassicRCEngine.saveHeat(ev.key,result,s,nowEpoch());try{ClassicRCAudio.heatResults(result);}catch{}competition().session=null;ClassicRCEngine.persist();render();}
  async function restart(){const c=competition(),ev=event();if(!c||!ev)return{ok:false,error:'Нет текущего заезда'};if(c.directorHold?.active)return{ok:false,error:'Сначала продолжите соревнование'};stopCountdown();stopTicker();try{ClassicRCAudio.cancel();}catch{}if(typeof raceTestSourceAdapter!=='undefined')raceTestSourceAdapter.stop();if(lapwiz.connected&&lapwiz.running){try{await lapwiz.stop();}catch{}}const res=ClassicRCEngine.restartCurrentEvent(nowEpoch());if(!res?.ok)return res;c.session=null;ClassicRCEngine.persist();render();return res;}
  function timerValue(){const ev=event(),s=session();if(!ev||!s)return'00:00';if(s.phase==='countdown')return`00:${String(Math.max(0,s.countdownLeft)).padStart(2,'0')}`;const rem=Math.max(0,durationMs()-elapsed(s));return fmtClock(rem);}
  function setSimulationSpeed(speed){const cfg=typeof raceTestSourceAdapter!=='undefined'?raceTestSourceAdapter.getConfig():null;if(!cfg)return 1;const next=[1,2,4,8].includes(Number(speed))?Number(speed):1;syncSessionScale(session());raceTestSourceAdapter.configure({...cfg,speed:next});ensureCompetitionClock();const s=session();if(s&&s.startedAtPerf){s.elapsedBeforePause=elapsed(s);s.startedAtPerf=performance.now();s.clockScale=next;}ClassicRCEngine.persist();if(typeof classicRCUpdateDynamic==='function')classicRCUpdateDynamic();return next;}
  function cycleSimulationSpeed(){const cur=testScale(),seq=[1,2,4,8],next=seq[(Math.max(0,seq.indexOf(cur))+1)%seq.length];return setSimulationSpeed(next);}
  function dispose(){stopTicker();stopCountdown();try{ClassicRCAudio.cancel();}catch{}if(typeof raceTestSourceAdapter!=='undefined')raceTestSourceAdapter.stop();}
  return Object.freeze({active,event,competition,session,ensureSession,pilots,liveRanking,elapsed,rawNowEpoch,nowEpoch,testSourceActive,testScale,beginStart,startNow,pause,resume,finish,stop,restart,processPass,processPilotStatus,handleSourceComplete,suggestedResult,saveResult,timerValue,checkLimit,startTicker,stopTicker,setSimulationSpeed,cycleSimulationSpeed,dispose,blank});
})();
